### ISSUE TITLE
Amazon Web Services  compatibility

### ISSUE THREAD

**Issue by hugo** [Keats/jsonwebtoken#102]
I'm working on a service that will sit in AWS, behind an ALB. Amazon [has a feature](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html) where you can to auth at the ALB, and your application will be provided with JWTs in specific headers. Unfortunately, the `x-amzn-oidc-data` header comes with incorrect base64 encoding, which means that spec-conformant libraries will not verify it's tokens.

Would you be willing to accept a patch that added an AWS-compat mode? I'm happy to write it, but I don't want to just open a PR if it's not a use case you're interested in supporting.

**Comment by Keats** [comment]
Is that still the case recently? I found https://github.com/brianloveswords/node-jws/pull/84#issuecomment-467770061
IMO it doesn't really makes sense to add support for a bug, in that link above they said they were changing it but it does suck :/

**Comment by hugo** [comment]
It's still an issue. They've at least acknowledged that it's a bug, but it's not looking like it will be fixed any time soon. Perhaps I'll just write a blog post and put up a demo repo showing how to work around the problem, while it persists.

**Comment by Keats** [comment]
I can add a link to that in the README when you publish it!
