### ISSUE TITLE
`exp` is validated as an opt-in option, which is different from the doc

### ISSUE THREAD

**Issue by samueltangz** [Keats/jsonwebtoken#104]
According to [the documentation](https://github.com/Keats/jsonwebtoken/tree/89fbd8f0ce5337d9bb2244007526a40bec1aa207#validation), it is stated that
> This library validates automatically the exp and nbf claims if present.

However, from the source code, it would be an opt-out option to validate `exp` claim, causing a disparency from the documentation and the actual logic.

https://github.com/Keats/jsonwebtoken/blob/89fbd8f0ce5337d9bb2244007526a40bec1aa207/src/validation.rs#L90
https://github.com/Keats/jsonwebtoken/blob/89fbd8f0ce5337d9bb2244007526a40bec1aa207/src/validation.rs#L105

**Comment by Keats** [comment]
The doc is wrong, I'll update it in the `next` branch. Thanks for noticing it!
