### ISSUE TITLE
How to generate ecdsa key pem ?

### ISSUE THREAD

**Issue by qmdx** [Keats/jsonwebtoken#111]
Please , How to generate ecdsa key pem ?

**Comment by Keats** [comment]
What do you mean?

**Comment by qmdx** [comment]
> What do you mean? Generating a pub/private ecdsa?

yes

**Comment by Keats** [comment]
https://wiki.openssl.org/index.php/Command_Line_Elliptic_Curve_Operations

**Comment by qmdx** [comment]
thank you very much.
