### ISSUE TITLE
Rust Security warning about spin

### ISSUE THREAD

**Issue by dessalines** [Keats/jsonwebtoken#114]
I got this error when running `cargo audit` on my project.

Spin looks like its abandoned, but there are alternatives.
https://rustsec.org/advisories/RUSTSEC-2019-0031.html

**Comment by Keats** [comment]
Ring is working on removing that dependency, nothing I can do about it. I'm not sure why an unmaintained crate would be a security vulnerability if no one found any issues though...

**Comment by Keats** [comment]
Ring related issue: https://github.com/briansmith/ring/issues/921

**Comment by Keats** [comment]
Closing as it seems like it will be fixed upstream and should be passed through automatically.
