### ISSUE TITLE
Implement PartialEq on ErrorKind

### ISSUE THREAD

**Issue by jamesjmeyer210** [Keats/jsonwebtoken#125]
I've started using this crate for a web service. Upon writing unit tests for some code I'd implemented around this crate, I quickly discovered `PartialEq` is not implemented on the `ErrorKind` enum. If it were implemented this would really make the tests a lot cleaner because the users of this crate wouldn't have to convert the errors to `String`/`str` for `assert_eq!` or `assert_ne!`

**Comment by Keats** [comment]
I don't think it can be implemented due to some error wrapping. I could be wrong though

**Comment by jamesjmeyer210** [comment]
Working with the strings isn't the end of the world, but I wouldn't be surprised if the missing `PartialEq` cascaded back on dependencies.

**Comment by platy** [comment]
The non-`PartialEq` wrapped error is `serde_json` which wraps `std::io::Error` which is not `PartialEq` https://github.com/serde-rs/json/issues/271

**Comment by Keats** [comment]
I'll take a PR for it
