### ISSUE TITLE
In README: deserialization of DateTime<Utc>

### ISSUE THREAD

**Issue by scastiel** [Keats/jsonwebtoken#129]
Hello! I’m very new to the Rust world, and I’m just trying to validate a JWT token in an API.

In the README, when defining the claims, I can read:

```rust
#[derive(Debug, Serialize, Deserialize)]
struct Claims {
    // ...
    exp: DateTime<Utc>,
    // ...
}
```

But actually just trying this with a standard JWT token ([like this one](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODg3Mzc2MDB9.yO4YrLk0TKUWBNZIg3BK84KwaqSNMIF4Eee2ZnQVCIU)), it doesn’t work and return an error:

```
Error: JSON error: invalid type: integer `1588737600`, expected a formatted date and time string or a unix timestamp at line 1 column 26
```

It took me a lot of time to figure out it is because `chrono` does not deserialize integers as timestamps by default, it suggests [using the `deserialize_with` attribute](https://docs.rs/chrono/0.4.11/chrono/naive/serde/ts_seconds/fn.deserialize.html).

So unless I misunderstood something, I think there are two ways of making it work:

- Either by specifying explicitly that the expiration date should be deserialized as a seconds timestamp:

```rust
// #[serde(deserialize_with = "from_ts")]
exp: DateTime<Utc>,
```

- Or using an integer:

```rust
exp: i64,
```

Both these options work with the validation.

In my opinion the README should be clear on these options, at least one of them if you prefer it? If you agree I’d be happy to submit a PR 🙂

**Comment by Keats** [comment]
I think we should link to https://github.com/Keats/jsonwebtoken/blob/master/examples/custom_chrono.rs if we want DateTime or use i64 in the README. Maybe even both to show the two options.
