### ISSUE TITLE
forked. Have features, want to contribute.

### ISSUE THREAD

**Issue by cmsd2** [Keats/jsonwebtoken#13]
https://github.com/cmsd2/rust-jwt

As discussed briefly out-of-band, I've been working on some features.

Off the top of my head, rsa, arbitrary Json payloads like the other jwt libs, claims parsing, serde, jwk keys and sets.

Can we pool efforts?

**Comment by Keats** [comment]
Thanks, a bit busy this week so i'll have a close look next week.

It does seem very different from a first look though!

**Comment by Keats** [comment]
- serde: good but it's a pain it's still not usable as simply on stable than on nightly :(, I see lots of custom implementation of the trait so I might stay on rustc-serialize for a bit unless there is a good reason to swap
- rsa: cool
- validation (of exp for example): nice, thought of doing that but wasn't sure whether it should be built-in or not
- jwk: i think that should not be in jwt, could have a rust-jwk that has rust-jwt as dependencies though
-arbitraty json: do you have a usecase for that?

**Comment by Keats** [comment]
I'm a bit busy with work and tera but i plan to get started with that when I have a bit more time.

Any thoughts on my comment above?

**Comment by cmsd2** [comment]
Serde seems quite a bit faster using your built-in benchmark.
You're right though, it was really quite hard work putting it in place -- I did it to get total control over the layout of the serialised json from a bunch of different datatypes.

Rsa: I think we're just getting started. I need to come up with a working example of code downloading and verifying a public cert to check the validity of a jwt.

re splitting the library up, I'd be open to doing that. I did want to see how it all looked when things came together. I was afraid that I'd cut the project along the wrong lines otherwise.

The arbitrary json payload does seem to be useful. I think that since a jwt can be used as any kind of token, like an access_token or id_token, and can be stored or forwarded, a client that receives one doesn't always need to use the contents. It's important to verify the signature, but the claims in the body of the token aren't always interesting to all parties.

**Comment by Keats** [comment]
Serde is faster (and better all around) but it's annoying to use if you are using stable. I keep seeing that the rust team is thinking of some integration for Serde but haven't seen anything new on that end so I might delay it a bit (despite using Serde in all of my other projects).

The goal of his lib is only jwt (equivalent of https://github.com/jpadilla/pyjwt and https://github.com/dgrijalva/jwt-go for example) so your needs will definitely exceed its scope so I think adding RSA signing first is the easiest step.

I'll have a look the RSA bit next week

**Comment by Keats** [comment]
with the macros 1.1 using serde on stable seems realistic! probably going to wait for that and move all the crates from rustc-serialize to serde when that happens

**Comment by cmsd2** [comment]
ah. macros 1.1 PR (i hadn't been following this). exciting stuff.
https://github.com/rust-lang/rfcs/pull/1681

**Comment by Keats** [comment]
I moved to ring for crypto, so would be nice to have ecdsa added as well later on.
The macros 1.1 rfc got accepted so using serde on stable should happen sooner than expected!

**Comment by cmsd2** [comment]
i've updated my stuff to latest versions of rustc, serde and openssl.
ring might be a good long term move. looks like it might do rs256 signatures already.
x509 would be nice though.
i'll take a look.

**Comment by Keats** [comment]
In terms of API I thought of having modules for each "algorithm".
So you would have `jsonwebtoken::hmac::{sign, verify}`, `jsonwebtoken::ecdsa::{sign, verify}` if we can't manage to keep a simple common API for all of them, which seems likely to happen

**Comment by briansmith** [comment]
Most likely, RSA support would require https://github.com/briansmith/ring/pull/226 which will probably land RSN.

**Comment by djc** [comment]
*ring*-0.4.1 was just released, which includes the RSA support you need for this.

**Comment by Keats** [comment]
Thanks for letting us know!

**Comment by cmsd2** [comment]
ring's still on my todo list :)
managed to get serde 0.9 to work at least.

**Comment by Keats** [comment]
@cmsd2 I've started work on that in https://github.com/Keats/rust-jwt/pull/23 but missing some features in the base64 crate right now
RSA and some JWT verification are next once it's in

**Comment by cmsd2** [comment]
serde works on stable now :)

**Comment by cmsd2** [comment]
hrm. ring seems a bit limited when it comes to juggling keys @briansmith 
i have the key's modulus and exponent etc in a jwk file and there's no way to create an rsa key pair from anything but a der file, and no way to create a der file.

**Comment by briansmith** [comment]
> hrm. ring seems a bit limited when it comes to juggling keys @briansmith
> i have the key's modulus and exponent etc in a jwk file and there's no way to create an rsa key pair from anything but a der file, and no way to create a der file.

For the specific case of verifying an RSA signature using the public key and modulus, see https://briansmith.org/rustdoc/ring/signature/primitive/fn.verify_rsa.html.

See https://github.com/briansmith/ring/issues/445 where we'll discuss the issue more generally.

**Comment by stephank** [comment]
@cmsd2 https://github.com/briansmith/ring/pull/441 should allow both dumping and loading RSA public keys. I've ported the bare-bones JWT implementation in Portier from openssl to that ring branch here: https://github.com/portier/portier-broker/pull/130. Curious to hear if this'll also solve your issue!

To get rid of the JWT code in Portier and move to this crate sounds nice, though there's a bunch of blockers. We'd have to depend on @cmsd2's branch, and are currently also stuck on Serde 0.8 because of toml. (On top of that, our current efforts to update other dependencies are already blocking on 3 crates. The list just keeps growing. 😆)

I may give it a try anyway, on a new branch with git dependencies. 😀

**Comment by Keats** [comment]
My attempt to move this crate to serde is also blocked for now by the base64 crate.

@stephank What exactly do you need from a JWT crate? My goal is to have something like https://github.com/jpadilla/pyjwt but typed. I'm not using RSA or ECDSA (@pimeys asked for that) myself but I'd like to add them so knowing what people need/want is helpful.

**Comment by pimeys** [comment]
Btw, a working ECDSA JWT implementation can be found here. https://gitlab.com/ilari_l/btls

Got it working with APNs and it wraps gnutls giving a quite nice interface.

**Comment by stephank** [comment]
@Keats Portier is pretty much OpenID Connect, both identity provider and relying party.

As an identity provider, it parses one or more private keys from PEM for signing, and exposes the public parts as JWKs in a `/keys.json` route. (We only use the first key to sign, but configuring multiple keys is useful for rotation.)

As a relying party, the upstream identity providers has a similar route to give us a list of JWKs it signs with. We get a token from upstream, look up the public key from the list, verify the signature and grab the claims.

Pyjwt is nice, and the rust-jwt API is already nice too. One small obstacle that both have right now is that we have to look up the public key based on `kid` and `alg`. That means that even with pyjwt, we have to do some manual parsing:

https://github.com/portier/demo-rp/blob/master/server.py#L269-L275

If that's something you want rust-jwt to support, there's really a bunch of options, and I'm not sure what the best approach would be. You could:

 - Offer a utility method to get just the header.
 - Allow passing a set of secrets to `decode`.
 - Make `decode` higher order, `secret: Fn(&Header) -> Option<(Algorithm, &[u8])>`

And I'm just thinking RSA here, maybe some of those options don't even work elsewhere.

**Comment by cmsd2** [comment]
that's something my fork might be able to do already: the decode method accepts a Verifier trait (which is in turn implemented for Signer traits).
if there's enough info in the header to make a local decision, you could multiplex several signers, selecting which to use based on the contents of the header,
then that delegate would lookup the private key from a list of keys you prepared earlier.

**Comment by cmsd2** [comment]
incidentally i was messing about with oidc when i figured i needed more complete jwt support. i got part way towards making an identity provider using iron but it was an uphill battle.

**Comment by Keats** [comment]
@stephank Would having 2 `decode` functions work? Since we don't have kwargs/default args it seems that the simplest way to do it would be to just have `decode` and `decode_without_verification` which both return the following struct:
```rust
#[derive(Debug)]
pub struct TokenData<T: Deserialize> {
    pub header: Header,
    pub claims: T
}
```
From there you can grab any field you want from the header, the downside being it's not the best performance as you deserialize the claims as well

**Comment by cmsd2** [comment]
Of course, another way to get noop verification might be to use the decode method that accepts a trait, and pass in a noop function.

**Comment by Keats** [comment]
I don't really want to add more params to the `decode` method though, the goal being to have the simplest API for 90% of the users.

I'm almost done adding RSA signing/verifying (DER format only for now, planning to add PEM as well) on #23 except that verifying doesn't currently work and I have no clear idea why, probably a silly mistake: https://github.com/Keats/rust-jwt/pull/23/files#diff-92706ffa42c53b037132b2e4c87f7eefR95

**Comment by chpio** [comment]
why not add 2 functions. the first one with a simple interface and default decoding, the second one which would take a custom decoder? (assuming noop decoding/verifying isn't the usual use case)

**Comment by stephank** [comment]
@Keats What @cmsd2 is suggesting would work like `ToSocketAddrs`: https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html

So:

```rust
pub trait ToAlgorithm {
    fn to_algorithm(self, &Header) -> Result<Algorithm, Error>;
}

pub fn decode<P: ToAlgorithm, T: Part>(token: &str, verify: P)
        -> Result<TokenData<T>, Error> {
    let header = /* decode header */;

    let alg = verify.to_algorithm(&header)?;

    /* verify signature */
    /* decode payload */
}
```

And then you'd have the identity implementation:

```rust
impl ToAlgorithm for Algorithm {
    fn to_algorithm(self, _: &Header) -> Algorithm { Ok(self) }
}
```

Which would allow:

```rust
jwt::decode(&my_token, jwt::Algorithm::HS256(&my_secret))
```

And then you could add an implementation for `FnOnce`, or even something else if that makes sense.

Making the secret a parameter of the algorithm enum would allow different kinds of secrets for different algorithms. (E.g. `Algorithm::RS256(&'a RSAPrivateKey)`.)

Regardless of all this, 'no verification' could simply be a `NoVerify` entry in the `Algorithm` enum.

**Comment by Keats** [comment]
I kinda like the Algorithm enum containing the key (granted it would need to be `[u8]` for most cases I think, unless the user wants to use ring to build the `RSAPrivateKey` themselves but that is more involved than just using `include_bytes!` The trait approach seems nice too, thanks for the detailed explanation.

Not sure about the `NoVerify` in the `Algorithm` enum though, there is already a `none` value in the JWT spec that jsonwebtoken doesn't support currently (and not planning to unless there is a compelling reason) and it could be ambiguous.

@briansmith is there a way to get more info on why `signature:verify` is failing? I believe https://github.com/Keats/rust-jwt/pull/23/files#diff-92706ffa42c53b037132b2e4c87f7eefR95 should work but it doesn't. The keys *look* fine and I can verify a JWT created with `jsonwebtoken` with `pyjwt` or jwt.io using the `.pem` public key.

**Comment by mike-engel** [comment]
Not sure if this helps, but the [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) project has two separate APIs: [verify](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) and [decode](https://github.com/auth0/node-jsonwebtoken#jwtdecodetoken--options). The naming there is pretty straightforward, and in that case, both return the payload.

If `rust-jwt` took the same approach with `decode` and `verify` functions that both returned the `TokenData` struct, I *think* that would solve the issue here of needing to get data before verifying it (which I've had to do before as well).

**Comment by Keats** [comment]
Hmm I quite like the `verify` vs `decode`

**Comment by mike-engel** [comment]
Yeah, that makes sense. `verify_and_decode` while explicit, is much too long. I do wonder if `verify` Is ok though, especially since it would probably return a Result type and the compiler would be enforcing that? I can't think of a better name at the moment that's descriptive yet concise

**Comment by Keats** [comment]
The v2 is getting close to done: https://github.com/Keats/rust-jwt/pull/23

It moves to Serde, adds validation, RSA signing/verification and allows you to just decrypt a token without verifying the signature (which should work for you @stephank):

```rust 
let token_data = decode::<Claims>(
     &token, 
     "secret", 
     Algorithm::HS256, 
     &Validation { validate_signature: false, ..Validation::default() }
);
```
Any feedback welcome!

**Comment by Keats** [comment]
Now available on crates.io as well: https://crates.io/crates/jsonwebtoken/2.0.0-beta-1
