### ISSUE TITLE
Consider renaming dangerous_unsafe_decode

### ISSUE THREAD

**Issue by LegNeato** [Keats/jsonwebtoken#130]
Thank you for this library! Would you consider renaming `dangerous_unsafe_decode` to `dangerous_insecure_decode`? "unsafe" has a specific meaning in Rust and it might be best not to overload it (it doesn't look like the implementation uses `unsafe` at a quick glance).

If you are interested, happy to put up a patch. If not, feel free to close!

**Comment by Keats** [comment]
It's unsafe because it doesn't verify the signature. Renaming it would be a breaking change though and unlikely to happen anytime soon. If you have a better name for it though, I can change it when the next major version happens.

**Comment by LegNeato** [comment]
Totally get it, but it isn't unsafe in the traditional Rust memory-safety sense. My suggestion as stated above to to replace "unsafe" with "insecure". If you agree it is a change you want, I can add a function named  `dangerous_insecure_decode` and make the existing `dangerous_unsafe_decode` function `#[deprecated(note = "Please use the dangerous_insecure_decode function instead"]`.

Then you can remove at the next major rev / at your leisure.

**Comment by Keats** [comment]
I like insecure!

**Comment by Keats** [comment]
If anyone is up for a PR, I'll merge it otherwise that will be in a few days.
