### ISSUE TITLE
Add struct of standard claims with common validation logic?

### ISSUE THREAD

**Issue by seanpianka** [Keats/jsonwebtoken#131]
I'm borrowing this idea from the [golang jwt implementation](https://github.com/dgrijalva/jwt-go/blob/master/claims.go#L18), where the package provides a struct which includes the "standard" public claims for all JWTs.

Essentially, instead of having all library users define their own copy of the default claims, i.e.
```rust
struct StandardClaims {
    aud: String,        // Optional. Audience
    exp: DateTime<Utc>, // Required (validate_exp defaults to true in validation). Expiration time
    iat: DateTime<Utc>, // Optional. Issued at
    iss: String,        // Optional. Issuer
    nbf: DateTime<Utc>, // Optional. Not Before
    sub: String,        // Optional. Subject (whom token refers to)
}
```
The crate instead can define this struct, perhaps making optional claims as `Option<T>`.

From that same Go file linked above, it also contains some helpful default methods for validation. These would also be useful to provide in `impl StandardClaims` to allow library users to not have to implement their own validation code (as provided in the examples). An example would be moving the `jwt_numeric_date` module into the library, and providing this custom serialization out of the box.

I'd be happy to contribute a PR, but would like to agree on a good way forward before doing so.

**Comment by Keats** [comment]
Those validations are already done in jsonwebtoken automatically without defining a struct, depending on the `Validation` struct and what there is in the jwt payload. https://github.com/Keats/jsonwebtoken/blob/master/src/validation.rs#L105-L170 is always called when decoding a JWT
