### ISSUE TITLE
dangerous_unsafe_decode variant with validation

### ISSUE THREAD

**Issue by giarc3** [Keats/jsonwebtoken#135]
I was wondering if it would be possible to add a variant of `dangerous_unsafe_decode` that includes validation (but still does not include signature verification). This would not be a breaking change as it would only involve adding new functionality.

The function signature would look like this:
```
pub fn dangerous_unsafe_decode_with_validation<T: DeserializeOwned>(
    token: &str,
    validation: &Validation
) -> Result<TokenData<T>>
```

My use case is this: Our SDKs accept a jwt as a function parameter which then gets sent to the server for verification. We want to allow the user to verify that their jwt is of a valid _form_ before sending to the server and potentially being rejected. I don't want to use the full `decode` function because I don't want to require them to create/provide a `DecodingKey`, and the server will do the signature verification regardless.

Thank you for your work on this project, and please let me know if I could be of any assistance implementing this feature.

**Comment by Keats** [comment]
It should be called `dangerous_insecure_decode_with_validation` (https://github.com/Keats/jsonwebtoken/issues/130) but why not.
