### ISSUE TITLE
Derive Hash for Header

### ISSUE THREAD

**Issue by giarc3** [Keats/jsonwebtoken#136]
Hi there,
Would it be possible to derive `Hash` for the `Header` struct? This would also require `Algorithm` to implement `Hash`, but should otherwise be easy. And it wouldn't require any breaking changes.

I'd be willing to open a PR for this if you're interested.

Thanks.

**Comment by Keats** [comment]
I don't see a reason not to? What's the usecase for hashing the header?

**Comment by giarc3** [comment]
Our usecase is pretty convoluted, but it boils down to generating Java bindings from our Rust structs, and we use the Rust implementation of `PartialEq` and `Hash` for Java's `hashCode()` and `equals()` functions. 
I admit it's not the most universal usecase, but as you said, I don't think there should be a reason not to.

**Comment by giarc3** [comment]
I have opened a PR for this. Please look it over when you have the time, it is a very minor change.
I would love if this could go out as 7.1.2 sometime soon. 
Thanks

**Comment by Keats** [comment]
It's done
