### ISSUE TITLE
About the need to implement the none algorithm

### ISSUE THREAD

**Issue by quentm74** [Keats/jsonwebtoken#140]
As I searched for a tool to encode / decode jwt, I found [jwt-cli](https://github.com/mike-engel/jwt-cli). This tool uses jsonwebtoken.

My goal was to test if an API refuses or not the "none" algorithm to test its security. But, I was not able to encode a jwt with the none algorithm with jwt-cli because the none algorithm is not supported by jsonwebtoken.

Should the none algorithm be implemented in jsonwebtoken ? I understand the unwillingness. However, it seems that implementing the none algorithm might be justifiable.

Let me know if I can help to add this feature ! Thanks for your job

**Comment by Keats** [comment]
I don't think it makes sense to implement the None algorithm in the library, with no algorithm it's easy to create a token manually and we avoid having footguns in the library.

**Comment by quentm74** [comment]
Thank you for your answer, I understand your point of view.

**Comment by felschr** [comment]
> I don't think it makes sense to implement the None algorithm in the library, with no algorithm it's easy to create a token manually and we avoid having footguns in the library.

I would argue since [Unsecured JWTs](https://datatracker.ietf.org/doc/html/rfc7519#section-6) are part of [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519) that they should be supported.

Related: https://github.com/Keats/jsonwebtoken/pull/45 https://github.com/Keats/jsonwebtoken/issues/124

**Comment by Keats** [comment]
> I would argue since [Unsecured JWTs](https://datatracker.ietf.org/doc/html/rfc7519#section-6) are part of [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519) that they should be supported.

Sure, just not in this library.

**Comment by alfalcon90** [comment]
See workaround here: https://github.com/Keats/jsonwebtoken/issues/124#issuecomment-2369633417
