### ISSUE TITLE
How can I validate custom claims?

### ISSUE THREAD

**Issue by michalskalski** [Keats/jsonwebtoken#144]
Hi, thank you for creating this jwt implementation. I wonder how could I extend validation part with additional checks which would validate my private custom claims? I tried to import https://github.com/Keats/jsonwebtoken/blob/master/src/serialization.rs#L24  and run extra validation after standard checks pass but this module is private.

**Comment by Keats** [comment]
When you decode a token, you get back the claims struct, you can run whatever validation you want afterwards on your own structs.

**Comment by michalskalski** [comment]
Thanks , will try use that approach.
