### ISSUE TITLE
Make get_current_timestamp() public

### ISSUE THREAD

**Issue by john01dav** [Keats/jsonwebtoken#152]
It would be convenient if [this](https://github.com/Keats/jsonwebtoken/blob/master/src/validation.rs#L100) function were public, for probably obvious reasons.

**Comment by Keats** [comment]
It's a one-liner from std and kind of a bit random to be public from jsonwebtoken I think

**Comment by john01dav** [comment]
It should be public since it gets it in the exact format that the library expects, thus preventing minor code duplication that can be problematic if someone misses some minor detail (e.g. as_micros() instead of as_secs()).
