### ISSUE TITLE
DecodingKey::from_rsa_components fails when modulus encoded with standard base64 character set

### ISSUE THREAD

**Issue by drocco007** [Keats/jsonwebtoken#153]
Hello!

**jsonwebtoken version**: 7.2.0
**rustc version**: rustc 1.47.0 (18bf6b4f0 2020-10-07)

I have built a token validator for tokens served from AWS Cognito [using their JWKS](https://cognito-identity.amazonaws.com/.well-known/jwks_uri). The validation steps are

* fetch the JWKs
* find the appropriate JWK data for the token (`decode_header`, extract `kid`, look up corresponding key in JWKs)
* pass the modulus and exponent to `DecodingKey::from_rsa_components`
* validate as usual

Out of the box, validation fails with a rather obscure `Error(Base64(InvalidByte(52, 43)))`. After digging into it for a while, I discovered that AWS Cognito JWKs are using the standard base64 character set, which trips up the `b64_decode` wrapper.

Here is a test case that demonstrates the same issue using the PKCS8 keypair in the test suite:

```rust
#[test]
fn rsa_modulus_exponent_standard_charset() {
    let privkey_pem = include_bytes!("private_rsa_key_pkcs8.pem");

    // modulus encoded as base64 from public_rsa_key_pkcs8.pem
    // $ openssl rsa -pubin -in public_rsa_key_pkcs8.pem -text -noout | egrep '^    ' | xxd -r -p | base64 | tr -d '\n'
    let n = "AMkROqx7jUdEGxztx9yrdqTihlYUKhmVyJznbkDcV87ipb0Ey1E7+JeLIIIefwmGIv3LyPkl1U/ZD1kil8SVwV3f+C5L3D7lGpAaAJH4fnohVTIdla1Mlso9zBZdB01RfSsEVywHMJERIkt56U4R0ciMbstGTHmX8VS+WqzIcNUkRCwfB6BnxvwLR/PQSBPYwwR2fXS3pSvWtfOMwH/C8KDy8byW9yJeZ53Kj3Enygw6HTBQSDHOJUMwyi+YL5oly1wdQBi5vCgY3xPLNy+caovslKHfo/DLbyI/NdnZEuEDIkVTf28tod2WPC2FRq6mV2U3IJ9ro5/Lio1y2VQ+U3U=";

    // $ openssl rsa -pubin -in public_rsa_key_pkcs8.pem -text -noout | awk '/Exponent/ { printf "0x%06x",$2 }' | xxd -r -p | base64
    let e = "AQAB";

    // transcoding the modulus into the URL safe charset allows the test to pass
    // let n = "AMkROqx7jUdEGxztx9yrdqTihlYUKhmVyJznbkDcV87ipb0Ey1E7-JeLIIIefwmGIv3LyPkl1U_ZD1kil8SVwV3f-C5L3D7lGpAaAJH4fnohVTIdla1Mlso9zBZdB01RfSsEVywHMJERIkt56U4R0ciMbstGTHmX8VS-WqzIcNUkRCwfB6BnxvwLR_PQSBPYwwR2fXS3pSvWtfOMwH_C8KDy8byW9yJeZ53Kj3Enygw6HTBQSDHOJUMwyi-YL5oly1wdQBi5vCgY3xPLNy-caovslKHfo_DLbyI_NdnZEuEDIkVTf28tod2WPC2FRq6mV2U3IJ9ro5_Lio1y2VQ-U3U=";

    let my_claims = Claims {
        sub: "b@b.com".to_string(),
        company: "ACME".to_string(),
        exp: Utc::now().timestamp() + 10000,
    };

    for &alg in RSA_ALGORITHMS {
        let token =
            encode(&Header::new(alg), &my_claims, &EncodingKey::from_rsa_pem(privkey_pem).unwrap())
                .unwrap();

        let token_data = decode::<Claims>(
            &token,
            &DecodingKey::from_rsa_components(n, e),
            &Validation::new(alg),
        )
        .unwrap();

        assert_eq!(my_claims, token_data.claims);
        assert!(token_data.header.kid.is_none());
    }
}
```

Test output:

```
$ cargo test
   Compiling jsonwebtoken v7.2.0 (/home/drocco/source/sandbox/rust/jsonwebtoken)
    Finished test [unoptimized + debuginfo] target(s) in 1.19s
     Running target/debug/deps/jsonwebtoken-a8164d7fdb367e8b
...
failures:

---- rsa::rsa_modulus_exponent_standard_charset stdout ----
thread 'rsa::rsa_modulus_exponent_standard_charset' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Base64(InvalidByte(52, 43)))', tests/rsa/mod.rs:173:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    rsa::rsa_modulus_exponent_standard_charset

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test lib'
```

Environment:

```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/drocco/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)

```

**Comment by Keats** [comment]
:(

I'm not sure how to fix that right now without making the crate less easy to use. Some kind of builder?

**Comment by sashaweiss** [comment]
I ran into a similar issue while writing some unit tests for code using this library. It doesn't seem to be an issue when using the full key data - I was able to create an `EncodingKey` using non-URL-safe base64 data, but when I try and make a `DecodingKey` using a modulus and exponent with non-URL-safe base64 data I got the same errors as above. Manually transcoding my modulus to URL-safe made it pass. (@drocco007, your post saved me a ton of time digging 😊)

Is there a reason those two types seem to behave differently for the base64 passed to them?

**Comment by Keats** [comment]
All the b64 handling in this crate is done via https://github.com/Keats/jsonwebtoken/blob/master/src/serialization.rs#L8-L14 so always expecting URL-safe base64 but I just noticed `EncodingKey::from_base64_secret` uses the b64 standard alphabet, is that what you meant @sashaweiss ?

**Comment by sashaweiss** [comment]
Thanks for the quick reply, @Keats!

Hmm, I was referring to the `EncodingKey::from_rsa_pem` method but from the code that appears to go a fairly different route (doing manual ASN.1 decoding?) so that answers that question!

Is there a reason the lines you linked above need to use `base64::URL_SAFE_NO_PAD`? It's not a big deal for my use case since the service I'll be integrating against appears to give back data in the URL-safe format regardless, so asking mostly as a curiosity.

**Comment by Keats** [comment]
> Is there a reason the lines you linked above need to use base64::URL_SAFE_NO_PAD?

**Comment by DanielJoyce** [comment]
Well its common for the token, but not necessarily for secrets in files. Those are usually plain base64

**Comment by Keats** [comment]
Those one use the default alphabet: https://github.com/Keats/jsonwebtoken/blob/master/src/encoding.rs#L25-L28

**Comment by erewok** [comment]
I just hit the same issue described here using JWKs from Okta (another common identity provider). I'm not sure what the suggested fix is based on the discussion here.

**Comment by Keats** [comment]
So in your case @erewok the JWK field in the header is using the standard base64 alphabet but the JWT itself URL safe?

**Comment by erewok** [comment]
I believe so, but to be honest I don't know what characters are allowed in the standard base64 alphabet: I've only ever encountered URL-safe base64.

For example, here are some sample JWKs from Okta:

```json
{"keys":[      {"kty":"RSA","alg":"RS256","kid":"LnZ0nk14LrHIA7lyiFFllB592tDn24fzhUCC15m8UEk","use":"sig","e":"AQAB","n":"jMv8vE2NRPOYqsz2TtKt_CnovScY0pORups3QTyzp5AKChLmoFfWn5uMvitUv888nhoPEJC4uhu9C9S4oJ87EEZkAII2sqXyfznGr2bWXczcXOUDXcWc8qGIjA8ZWA-z9iPMdvTUfdU_OuwdSrIyOQKbgSaFQlW93G3wd2oB85npSlSf_l-MRQFd8TlMlRUnavfamxksjImbnnJyCWJbyznhHFGKpGJM2uqDmuqbFcJpO3iajlMiU0NIEHGgju9WSmojdfLBQY5xub4vPx3CxQ4uYboO5PAm8ayZcWO-LTIm7kV3B2jgP3MOnF8zgu6sZWMK6IOT9s1WNwOql1Hs8Q"},        {"kty":"RSA","alg":"RS256","kid":"w3kmXCauiXV5mBjQr5FPDM6shLzWb6STI0HE0U2irmg","use":"sig","e":"AQAB","n":"qDa0QJ2LAvLEQ3dKDc4J2CUU4lBOzTChmrNVA3v_-TPoKdWZX1FptdC0PwAK8D3GeLPlOuTjcBgRYuaIP7ozgkdqk3STRpzPVoVSde9PtSrtyag6p_PSpx7KQQwVu3s9fm07rgmmhjjzLzsbGECt2mp2K3ycaN3Etsdv0XTG-_MqcpU_fiB6lFsl7RykNHEFdRCFublSVgPY4_X-6-XJSVckqv6AlLWP4Pw13nkVxwXhuDmg_LpzQgs5Ghr7vqYe8mZ3T10jaO1HMnHbZleuj1Qfo7cATJqcM8Pt2u5UKPC_HCPILtBSjPp9RPpEqDUfdPow8nMsZyyhaYeY2RmO8w"}
]}```

I was looking for other examples, and I found this [archived repo](https://github.com/tazjin/alcoholic_jwt/blob/master/src/lib.rs) which appears to be doing something similar (it is calling out to `openssl`, though). I was planning to try this today, but it too looks to be using `base64::URL_SAFE_NO_PAD`, so if this works for me, then my issue may lie elsewhere. I expect that the code in this library will also fail with `Error(Base64(InvalidByte`...

**Comment by Keats** [comment]
> I believe so, but to be honest I don't know what characters are allowed in the standard base64 alphabet: I've only ever encountered URL-safe base64.

The standard allows `+` and `/` while URL safe is `-` and `_`. Since there are `_` and `-` in that string that's likely URL safe.
Try to use https://github.com/marshallpierce/rust-base64 directly and see what happens with the various alphabets

**Comment by erewok** [comment]
My apologies: my sample **JWT** was in a test file and it appears that it was incorrectly formatted. I kept getting `Error(Base64(InvalidByte` errors but it _wasn't_ due to the **JWK**. It was whenever I tried to verify my JWT. After various experiments and finally breaking out each step, I was able to ascertain that my validation step was failing. With a correctly formatted JWT, I was able to run validation with a JWK like this:

```rust
        let decode_key_og = jsonwebtoken::DecodingKey::from_rsa_components(jwk.n.as_str(), jwk.e.as_str());
        let validation = jsonwebtoken::Validation::new(header.alg);
        jsonwebtoken::decode(token, &decode_key_og, &validation)
            .map_err(|err|  errors::Error::JWTError(err))
```

Apologies for the distraction here: it looks like my JWKs _are_ url-safe encoded.

**Comment by linnal** [comment]
I'm having the same problem, some times the decoding works some times it does not. This is the token I'm using right now with google authentication: 

```
eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5ZWQ1N2Y0MjQ0OTEyODJhMTgwMjBmZDU4NTk1NGI3MGJiNDVhZTAiLCJ0eXAiOiJKV1QifQ.ewogICJpc3MiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tIiwKICAiYXpwIjogImF6cCIsCiAgImF1ZCI6ICJhdWQiLAogICJzdWIiOiAiMTA0MzUyNzcxNTU5Mzg4NTM1ODg4IiwKICAiZW1haWwiOiAiZWlAZ21haWwuY29tIiwKICAiZW1haWxfdmVyaWZpZWQiOiB0cnVlLAogICJuYW1lIjogImUgaSIsCiAgInBpY3R1cmUiOiAiIiwKICAiZ2l2ZW5fbmFtZSI6ICJlIiwKICAiZmFtaWx5X25hbWUiOiAiaSIsCiAgImxvY2FsZSI6ICJlbi1HQiIsCiAgImlhdCI6IDE2MjA5MjUyMjAsCiAgImV4cCI6IDE2MjA5Mjg4MjAKfQ.iRGsxTzRHmAc3xxwfAdqNOwhaFnf2UHK2ufSTDJapdu5ibJGiHIpzXEYVDg9hQ_hXge5zuVazI1RZjeronqh2Mb7oZttLXcdLEcaiZpSjdB019zkXxO5n8LvA6HBRKGj51JaQGP32Z2vjGGXsqJGFDxgWzeek8t_WjSoHpjB23Vq5gw7jNrt03p1e2_HAkyvFO_hQQyB7py5o64YqHq3lGvtY8FtyTF4NBdYaV_PMDrh2KPhGaSx5Ux
```

The token is dived in 3 parts, the first 2 are ok, but the third one fails as it is not a valid base64 format. Although if I use this online tool [https://jwt.io/](https://jwt.io/) it does not complain and everything seem to be decoded. 

This is what I'm doing from the code

```
let token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5ZWQ1N2Y0MjQ0OTEyODJhMTgwMjBmZDU4NTk1NGI3MGJiNDVhZTAiLCJ0eXAiOiJKV1QifQ.ewogICJpc3MiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tIiwKICAiYXpwIjogImF6cCIsCiAgImF1ZCI6ICJhdWQiLAogICJzdWIiOiAiMTA0MzUyNzcxNTU5Mzg4NTM1ODg4IiwKICAiZW1haWwiOiAiZWlAZ21haWwuY29tIiwKICAiZW1haWxfdmVyaWZpZWQiOiB0cnVlLAogICJuYW1lIjogImUgaSIsCiAgInBpY3R1cmUiOiAiIiwKICAiZ2l2ZW5fbmFtZSI6ICJlIiwKICAiZmFtaWx5X25hbWUiOiAiaSIsCiAgImxvY2FsZSI6ICJlbi1HQiIsCiAgImlhdCI6IDE2MjA5MjUyMjAsCiAgImV4cCI6IDE2MjA5Mjg4MjAKfQ.iRGsxTzRHmAc3xxwfAdqNOwhaFnf2UHK2ufSTDJapdu5ibJGiHIpzXEYVDg9hQ_hXge5zuVazI1RZjeronqh2Mb7oZttLXcdLEcaiZpSjdB019zkXxO5n8LvA6HBRKGj51JaQGP32Z2vjGGXsqJGFDxgWzeek8t_WjSoHpjB23Vq5gw7jNrt03p1e2_HAkyvFO_hQQyB7py5o64YqHq3lGvtY8FtyTF4NBdYaV_PMDrh2KPhGaSx5Ux";
let validation = Validation::new(Algorithm::RS256);
let n = "vFRvKlxctMszRPK6iZ9TGW3lLLIvun157Lgb_M3LDBZpNcmnMDgswiIjEODSdclMv_gj6UWpoX7qWFHA-PNi_KQtyZMaDSrpNL3eA5zjbPA3CV6fGaWCBzallSjHo9Z7E9-Kqtn0IMmIcNxADo2RUSoYxb3n8ivjA38m8cnJ_yFEm99LXqBy5ZPhFiPOxNcxGwkkVsjiTUbCcaIb4mk2owD1XjPGmV4EJdICXbyG7e4Lp4jX7MegzEJrDQKoq4mMqVt6fHLuma_GSG7W1gV_Zs71SZ6RufB2LJQMPChg2qyfWeetwsIqAJoxtTxEipjlCT-8-QHV_QQw56MmiK_Txw";
let e = "AQAB";

let decode_key = DecodingKey::from_rsa_components(&n, &e).unwrap();
println!("{:?}", &decode_key);
```
I'm only using google token at the moment and with some tokens the decoding is successful but with some others it fails, always decoding the third part (signature).  
For privacy I did change the payload data, but header and signature are unchanged.

**Comment by Keats** [comment]
So it looks like google doesn't add the padding to base64 for some reasons. I guess we should pad the segments before trying to decode them.

Essentially doing:

```
    rem = len(input) % 4

    if rem > 0:
        input += b"=" * (4 - rem)
```
before decoding it (taken from pyjwt)

**Comment by linnal** [comment]
@Keats I tried to do that from my code but it does not seem to change anything. 

```
let mut token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5ZWQ1N2Y0MjQ0OTEyODJhMTgwMjBmZDU4NTk1NGI3MGJiNDVhZTAiLCJ0eXAiOiJKV1QifQ.ewogICJpc3MiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tIiwKICAiYXpwIjogImF6cCIsCiAgImF1ZCI6ICJhdWQiLAogICJzdWIiOiAiMTA0MzUyNzcxNTU5Mzg4NTM1ODg4IiwKICAiZW1haWwiOiAiZWlAZ21haWwuY29tIiwKICAiZW1haWxfdmVyaWZpZWQiOiB0cnVlLAogICJuYW1lIjogImUgaSIsCiAgInBpY3R1cmUiOiAiIiwKICAiZ2l2ZW5fbmFtZSI6ICJlIiwKICAiZmFtaWx5X25hbWUiOiAiaSIsCiAgImxvY2FsZSI6ICJlbi1HQiIsCiAgImlhdCI6IDE2MjA5MjUyMjAsCiAgImV4cCI6IDE2MjA5Mjg4MjAKfQ.iRGsxTzRHmAc3xxwfAdqNOwhaFnf2UHK2ufSTDJapdu5ibJGiHIpzXEYVDg9hQ_hXge5zuVazI1RZjeronqh2Mb7oZttLXcdLEcaiZpSjdB019zkXxO5n8LvA6HBRKGj51JaQGP32Z2vjGGXsqJGFDxgWzeek8t_WjSoHpjB23Vq5gw7jNrt03p1e2_HAkyvFO_hQQyB7py5o64YqHq3lGvtY8FtyTF4NBdYaV_PMDrh2KPhGaSx5Ux";

let rem = token.len() % 4;
if rem > 0 {
    token = token +  &"=".repeat(4 - rem);
} // it does add "===" in the end of the token

for p in token.split('.'){
     println!("\n{}\n\t{:?}\n",p, base64::decode_config(p, base64::URL_SAFE));
}
```

Header and paylaod are valid but signature still gives `Err(InvalidByte(247, 61))`

**Comment by linnal** [comment]
Please ignore my comments :/ I'm really sorry! It was a problem with my terminal. It took me a while to understand that the token output was being cut and the signature was incomplete :(

**Comment by Keats** [comment]
ah so it works in the end?

**Comment by linnal** [comment]
yap, it works!
