### ISSUE TITLE
Support for Refresh Token

### ISSUE THREAD

**Issue by chinmayyadav** [Keats/jsonwebtoken#155]
Hi guys, I am trying to implement JWT in my rust web application and I am using this library.
I was able to successfully generate a token and use it for verification, but I was wondering whether there is any support to differentiate and create an access token and a refresh token separately as there is in flask_jwt in python?
I could not find it in the documentation anywhere.
I am relatively new to rust, so forgive me if I missed it somewhere.
If anyone could tell me how can I implement something like this or guide me to any example, I would really appreciate it.

Thanks

**Comment by Keats** [comment]
No it's not meant to be implemented in this library but it could in a higher level lib.

**Comment by chinmayyadav** [comment]
Okay, Thanks
