### ISSUE TITLE
Decode arbitrary payload

### ISSUE THREAD

**Issue by superstator** [Keats/jsonwebtoken#156]
I'd like to use `jsonwebtoken` to decode a JWT with an arbitrary payload, and just return that payload as a string. I still want to verify the signature, but I don't want to look for keys like `iat`, `exp`, etc. In fact I'd like to handle cases where the payload isn't JSON at all, or may be malformed JSON. Is this possible? If not, would you be open to a PR?

**Comment by Keats** [comment]
In that case it's easier to skip this crate and just split on `.` and decode base64

**Comment by superstator** [comment]
But I do need signature verification, and just I don't want to actually decode/deserialize anything. You have a `verify` fn in `/src/crypto/mod.rs` that does most of what I need, though it would be nice to also use your code for error handling and splitting up the JWT compact string. Basically, everything in `jsonwebtoken::decode` but the last couple lines, call it something like `jsonwebtoken::verify_sig`.

I actually have it working in a fork, happy to send a PR or a link, if that would make it clearer what I'm trying to do.

**Comment by Keats** [comment]
Ok, I'll take a PR
