### ISSUE TITLE
Add support for RSA256 1024 bit key support

### ISSUE THREAD

**Issue by shuoli84** [Keats/jsonwebtoken#157]
Current implementation forbidden 1024 bit keys, consider loose the leash by use ring algorithm RSA_PKCS1_1024_8192_SHA256_FOR_LEGACY_USE_ONLY instead of RSA_PKCS1_2048_8192_SHA256?

**Comment by briansmith** [comment]
Why would anybody be using RSA 1024 with JWT, except as a mistake?

**Comment by shuoli84** [comment]
I can't answer that, but there are external systems I can not control, besides, ring added this support for some reason I guess?

**Comment by briansmith** [comment]
> ring added this support for some reason I guess?

I added it only because some some TLDs use 1024-bit RSA signatures for DNSSEC.

Anyway, most JWT users will NOT want to accept 1024-bit keys, so if 1024-bit key support were added to this crate, it should be something that is opt-in on a per-verification basis.

**Comment by shuoli84** [comment]
I see, then maybe create a new algo variant with RS256_Legacy which user has to overwrite explicitly is a better idea?

**Comment by Keats** [comment]
I would be hesitant to add that at all. Since it's pretty niche (never seen that before), I would rather have people fork this crate than having it in and be confusing/insecure. As the PR shows, it's an easy change

**Comment by shuoli84** [comment]
@Keats that makes sense too. I'll keep the fork and use it for now.
