### ISSUE TITLE
Consider expose readable error messsage when signature validation failed?

### ISSUE THREAD

**Issue by shuoli84** [Keats/jsonwebtoken#158]
The code verify_ring converts result to bool, which actually eats all underlying errors. E.g, the error key_too_small, is not signature err but key err. 

```rust
/// See Ring docs for more details
fn verify_ring(
    alg: &'static dyn signature::VerificationAlgorithm,
    signature: &str,
    message: &str,
    key: &[u8],
) -> Result<bool> {
    let signature_bytes = b64_decode(signature)?;
    let public_key = signature::UnparsedPublicKey::new(alg, key);
    let res = public_key.verify(message.as_bytes(), &signature_bytes);

    Ok(res.is_ok())
}
```

**Comment by Keats** [comment]
I'd take a PR for it but it's probably a breaking change?

**Comment by shuoli84** [comment]
Hmm, I think this is not a breaking change but a bug fix, if we only convert signature err to bool. If it is ok, I can create a pr for this.

**Comment by Keats** [comment]
Actually `res` would be a `error::Unspecified` in case of an error so we don't lose anything afaik?

**Comment by shuoli84** [comment]
Yea, double checked the code, you are right.
