### ISSUE TITLE
`map_err(|_| ...)` is an anti-pattern

### ISSUE THREAD

**Issue by arniu** [Keats/jsonwebtoken#164]
`map_err(|_| ...)` is an anti-pattern, which lose detail about the failure.

**Comment by Keats** [comment]
But in more practical terms about this repo?

**Comment by arniu** [comment]
There are two cases in the repo, which convert different failures to simple `InvalidRsaKey` errors. As a result, it's difficult to debug. For example, #151 .

https://github.com/Keats/jsonwebtoken/blob/90b97007484e782994120587e751108819b7aa50/src/crypto/rsa.rs#L42

> Parse key every signing!
> Maybe move to `EncodingKey`?

https://github.com/Keats/jsonwebtoken/blob/90b97007484e782994120587e751108819b7aa50/src/crypto/rsa.rs#L48

> `InvalidRsaKey` here is weired.

**Comment by Keats** [comment]
ah I see, that should be easy to fix in the v8 branch. It was probably copied from the ring docs example.
