### ISSUE TITLE
Bump ring dependency to 0.16.19

### ISSUE THREAD

**Issue by andrekorol** [Keats/jsonwebtoken#166]
Bumping [ring](https://github.com/briansmith/ring) to 0.16.19 would fix compilation issues on crates that depend on jsonwebtoken as seen on [Compilation fails on aarch64-apple-darwin](https://github.com/briansmith/ring/issues/1063#issue-723460081) and [Build fail on Apple Silicon](https://github.com/briansmith/ring/issues/1163#issue-773901788).

**Comment by ephemer** [comment]
@andrekorol I'm new to rust and blocked by this issue. That said, I can see that rust is already trying to compile `ring v0.16.20` without this change and it still errors out:

```
error[E0432]: unresolved import `super::sysrand_chunk`
   --> /Users/geordiejay/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/rand.rs:306:16
    |
306 |     use super::sysrand_chunk::chunk;
    |                ^^^^^^^^^^^^^ could not find `sysrand_chunk` in `super`
    ```

**Comment by andrekorol** [comment]
@ephemer I'm also building from an M1 Mac and my build that depends on this jsonwebtoken crate still fails...
