### ISSUE TITLE
Add x5c Header

### ISSUE THREAD

**Issue by olitha** [Keats/jsonwebtoken#181]
The x5c Header contains a certificate chain as base64 encoded DER certificates and can be used outside the jsonwebtoken lib to get the public key for signature verification.
Additionally the certificate chain can be verified by the application.

Can we add the x5c header? Only to make it available to applications?

**Comment by jnicholls** [comment]
Wow, I literally implemented this last night with the intention to open an issue and submit a PR this morning. However, I did it differently and I think more correctly. I will submit my PR shortly after I rebase with your update.

**Comment by jnicholls** [comment]
@Keats Do you like to close out these issues once a release is done, or after code is in `next`? I'll quickly take the opportunity to say thanks for your contributions to the community as well!

**Comment by Keats** [comment]
Forgot to reply! Thanks for the kinds words, I'll close all relevant issues on release - probably this weekend if nothing else pops up.
