### ISSUE TITLE
jsonwebtoken invalid a valid signature

### ISSUE THREAD

**Issue by zuoziqi** [Keats/jsonwebtoken#183]
I have a generated OAuth2.0 JWT Token, this token has been validated by jwt.io but decode function return error with ErrorKind::InvalidSignature. This token was encrypted by HS256 and I have set the correct secret key acquired from OAuth2 Server.
Related code followed:
```rust
static SECRET_KEY: &str = "88c71f43-0358-4b08-9cf2-f53d98637514";
match decode::<Claims>(
                        token.as_ref(),
                        &DecodingKey::from_secret(SECRET_KEY.as_ref()),
                        &Validation::new(Algorithm::HS256),
                    ) {
                        Ok(claim) => rocket::outcome::Outcome::Success(claim.claims),
                        Err(err) => {
                            error!("Token校验错误:token:{} error: {}", token, err);
                            rocket::outcome::Outcome::Failure((
                                rocket::http::Status::Unauthorized,
                                err,
                            ))
                        }
                    }
```
The validated token:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijg4YzcxZjQzLTAzNTgtNGIwOC05Y2YyLWY1M2Q5ODYzNzUxNCJ9.eyJleHAiOjE2MTQ5NDEyNzgsImlhdCI6MTYxNDk0MDk3OCwianRpIjoiMTk0MDNhZWUtZTNmOS00YmQwLWEzZjctN2QwOWZjYjcyMDUyIiwiaXNzIjoiaHR0cHM6Ly9pZHAuYXEtamsuY29tL2F1dGgvcmVhbG1zL01vbml0b3JTeXN0ZW0iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNGY2YTE2ZjYtOWE3OC00OTZmLWI3NzAtYjc4MmQ4YjJkYjZjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibW9uaXRvci11aSIsInNlc3Npb25fc3RhdGUiOiIzZTM1NjQ0ZC03MDMyLTQ4MzEtOTVjMC04OWVmMDRiNmM4ZDgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vYWRtaW4uYXEtamsuY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJNQUlOVEFJTiIsIkFETUlOIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im1vbml0b3Itc2VydmVyIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6ImFkbWluIiwibG9jYWxlIjoiemgtQ04iLCJlbWFpbCI6ImFkbWluQGFxLWprLmNvbSJ9.83gwB8KkhQuYgki0dLh2X1CbDeIhhnbRK5GU9OIzjU8`

**Comment by Keats** [comment]
@zuoziqi what was the issue?
