### ISSUE TITLE
How to create a non-expiring token ?

### ISSUE THREAD

**Issue by ahmed-yasen-va** [Keats/jsonwebtoken#188]
I am trying to create a non-expiring token by adding 0 to the exp claim but the result is an ExpiredSignature Err.

**Comment by Keats** [comment]
Just add a timestamp in the year 3000 or something

**Comment by ahmed-yasen-va** [comment]
Does this crate depend on the epoch timestamp?

**Comment by Keats** [comment]
Yes, it's from the JWT spec. So 0 would be 1970

**Comment by ahmed-yasen-va** [comment]
I think putting the timestamp in the year 3000 or beyond the year 2038 may cause problems. Because the epoch time will overflow on 21 Jan 2038.

**Comment by ahmed-yasen-va** [comment]
I suggest making the 0 exp be a non-expiring token. In any way, there is no one create an already expired token.

**Comment by Keats** [comment]
> I suggest making the 0 exp be a non-expiring token.

No, 0 is a valid timestamp even if a useless one.
