### ISSUE TITLE
Add x5t#S256 header

### ISSUE THREAD

**Issue by Ten0** [Keats/jsonwebtoken#201]
There are a few headers defined in https://datatracker.ietf.org/doc/html/rfc7515#section-4 that are not declared in [`Header`](https://docs.rs/jsonwebtoken/7.2.0/jsonwebtoken/struct.Header.html).

Specifically, we use Sha256 thumbprints to identify certificates in our system, and would like to propagate that to the JWTs.

It would be great to either:
 - Add fields defined by the norm to the Header
 - Make Header generic and `#[serde(flatten)]` to allow people to deserialize other fields from the header.

**Comment by Keats** [comment]
Can you do a PR for 1 on the `next` branch?
