### ISSUE TITLE
validating Audience should take HashSet<&str> type instead of HashSet<String>

### ISSUE THREAD

**Issue by DanielJoyce** [Keats/jsonwebtoken#204]
That way the hashSet can be declared as a constant and reused.

In general the various string pointer types should be favored over String

Basically this doesn't work.

``` rust
const JWT_AUDIENCE: HashSet<String> = hashset! {String::from("phylum_api")};
```

The same applies to validating issuer as well.

**Comment by Keats** [comment]
The recommended way to set those fields is to use the methods: https://docs.rs/jsonwebtoken/8.0.0-beta.2/jsonwebtoken/struct.Validation.html#implementations.
Why not have the full validation be `const` or `lazy_static` or `once_cell`? You shouldn't need to have multiple `Validation` struct for the same JWT kind.
