### ISSUE TITLE
Allow newer ring fix versions

### ISSUE THREAD

**Issue by TheDan64** [Keats/jsonwebtoken#206]
Hi, currently ring is tied to 0.16.5. This is conflicting with another dependency of mine which requires `0.16.11 <= ring < 0.17`

Would it be possible to release a new version of v7 of the crate with `^0.16.5` specified? I think that would loosen the constraint to `0.16.5 <= ver < 0.17`?

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

**Comment by a1ien** [comment]
>The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement.

**Comment by TheDan64** [comment]
Oh, interesting
