### ISSUE TITLE
Signing JWTs for AzureAD authentication

### ISSUE THREAD

**Issue by Occhioverde** [Keats/jsonwebtoken#209]
Good morning.

I'm trying to authenticate my Rust application to Microsoft Azure AD using the [certificate credentials method](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials) but the creation of the EncodingKey struct keeps panicking with the "InvalidKeyFormat" error.

I've read [here in the issues](https://github.com/Keats/jsonwebtoken/issues/77#issuecomment-579623847) that X.509 isn't supported but since the cited conversation was about decoding, and I found the possibility to set the [x5t header filed](https://docs.rs/jsonwebtoken/7.2.0/jsonwebtoken/struct.Header.html#structfield.x5t), I was wondering if things changed or if the problem I linked above only applies when decoding.

Here you can find some relevant pieces of code:
- How I'm trying to initialize the EncodingKey struct in Rust:
  
  ```rust
  let mut cert_file = File::open(xdg_dirs.find_config_file("cert.pem").unwrap()).unwrap();
  cert_file.read_to_end(&mut cert_bytes).unwrap();
  let key = jsonwebtoken::EncodingKey::from_rsa_pem(&cert_bytes).unwrap();
  ```
- The command I used to generate the certificate:
  
  ```bash
  openssl req -x509 -days 3650 -newkey rsa:2048 -keyout ./cert/key.pem -out ./cert/cert.pem
  ```
- Working JS code that can sign the JWT with the same certificate
  
  ```javascript
  const cert = fs.readFileSync('./cert/key.pem');
  const signedToken = jwt.sign(jwtPayload, { key: cert, passphrase: global.config.graphAuth.certPassphrase } , {
    algorithm: "RS256",
      header: {
        x5t: global.config.graphAuth.certFingerprint
    }
  });
  ```
Many thanks in advance to anyone that can help me solve this problem.

**Comment by Keats** [comment]
The field x5t can be set but x509 is still not supported for encoding/decoding

**Comment by Occhioverde** [comment]
> The field x5t can be set but x509 is still not supported for encoding/decoding

Thank you very much for the information.

May I ask if there any plans to support X509 encoding and decoding (even if in the long term)?

**Comment by Keats** [comment]
Not by me but if someone does a PR wth tests there are no reasons to not merge it

**Comment by Occhioverde** [comment]
> Not by me but if someone does a PR wth tests there are no reasons to not merge it

Of course. Thanks again.
