### ISSUE TITLE
JWT Parsing fails when exp is a float

### ISSUE THREAD

**Issue by emeryc** [Keats/jsonwebtoken#212]
I was trying to figure out if people in my company were crazy, or if this was a part of the spec. Turns out that float times are part of the spec as mentioned in this bug report on somebody else's JWT library in a different language. https://github.com/open-policy-agent/opa/issues/1296#issue-426476169

This is causing me a bit of a problem because others in my company are using float JWTs because javascript libraries and java libraries think that this is a feature.

I'm happy to open a PR and just change the times from u64 to f64. Or any other answer that you think is better.

**Comment by Keats** [comment]
It's released in v8 beta 5
