### ISSUE TITLE
Multiple issuers?

### ISSUE THREAD

**Issue by vanillajonathan** [Keats/jsonwebtoken#216]
This is not a feature request, just some food for thought. 🧠️💡️

Microsoft's `Microsoft.IdentityModel.Tokens` JWT library supports multiple issuers.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validissuers

```cs
public string ValidAudience { get; set; }
public IEnumerable<string> ValidAudiences { get; set; }
public string ValidIssuer { get; set; }
public IEnumerable<string> ValidIssuers { get; set; }
```

Which in Rust would be:
```rust
pub valid_audience: Option<String>,
pub valid_audiences: Option<HashSet<String>>,
pub valid_issuer: Option<String>,
pub valid_issuers: Option<HashSet<String>>,
```

Another interesting thing is that Microsoft have a default leeway of 5 minutes.
[TokenValidationParameters.cs#L130-L134](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/38fa6df0aaef049bff548870191400507b3753f4/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L130-L134)

**Comment by Keats** [comment]
It's already supported: https://docs.rs/jsonwebtoken/8.0.0-beta.5/jsonwebtoken/struct.Validation.html#method.set_iss and https://docs.rs/jsonwebtoken/8.0.0-beta.5/jsonwebtoken/struct.Validation.html#method.set_audience

**Comment by vanillajonathan** [comment]
My bad, I checked the master branch, not the next branch.

Another interesting thing is that Microsoft have a default leeway of 5 minutes.
[TokenValidationParameters.cs#L130-L134](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/38fa6df0aaef049bff548870191400507b3753f4/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L130-L134)

**Comment by Keats** [comment]
The current default of 0 is probably not good enough but 5 minutes seem a bit long

**Comment by vanillajonathan** [comment]
Maybe 1 or 2 minutes is more reasonable.

**Comment by Keats** [comment]
I've set it to 1 minute in the v8 beta

**Comment by vanillajonathan** [comment]
What is the roadmap for 8? when is the release?

**Comment by Keats** [comment]
Pretty soon I think. One of the last thing was https://github.com/Keats/jsonwebtoken/pull/225
Once this is merged I'll release the last beta and let people use the beta a bit. 
Note that the current last beta version on crates.io has a bug with issuers validation that is already fixed in the repo in case you try it.
