### ISSUE TITLE
Implement Clone and Eq for error type

### ISSUE THREAD

**Issue by qwandor** [Keats/jsonwebtoken#217]
It would be helpful if `jsonwebtoken::error::Error` implemented `Clone` and `Eq`.

**Comment by Keats** [comment]
I would take a PR for it on the `next` branch.

**Comment by qwandor** [comment]
I've sent a PR for `Eq`.

It turns out `Clone` is more difficult, because `serde_json::Error` doesn't implement `Clone`. I can see two ways around this:
1. Convert the `serde_json::Error` to a `String` and just wrap that instead. This would lose the ability to convert back to the `serde_json` type or get whatever other information it has.
2. Wrap it in an `Arc`. I'm inclined to go with this option.

**Comment by qwandor** [comment]
I've gone ahead and gone the `Arc` route, I think it's a reasonable workaround.
