### ISSUE TITLE
Why is `EncodingKey`'s `content` attribute private?

### ISSUE THREAD

**Issue by Xithrius** [Keats/jsonwebtoken#223]
It doesn't seem like there's any way to access [`content`](https://github.com/Keats/jsonwebtoken/blob/master/src/encoding.rs#L10-L16). 

Would it be possible to make it public, or is there a reason to keep it's current state?

Thanks!

**Comment by Keats** [comment]
Any reason to be able to access it? Those structs are not meant to be used outsde of encode/decode

**Comment by Xithrius** [comment]
@Keats Thanks for the quick response! Originally I'd use this for [octocrab's `create_jwt` function](https://github.com/XAMPPRocky/octocrab/blob/master/src/auth.rs#L36-L61), but I've realized that it's different than the one on [docs.rs](https://docs.rs/octocrab/0.13.0/src/octocrab/auth.rs.html#22-46).

There is no need for access of this attribute, I was interpreting how to use the function incorrectly based on inconsistent sources.

Have a good one!
