### ISSUE TITLE
Support for mips Please!!

### ISSUE THREAD

**Issue by xdrghbjiikmdghu** [Keats/jsonwebtoken#227]
Help please .The dependencie ring does not support for mips. So How can i use jsonwebtoken for  mips?

**Comment by Keats** [comment]
If ring doesn't support mips then you can't. Maybe it will be possible to switch to rust-crypto crates if they have been audited but not for now.

**Comment by xdrghbjiikmdghu** [comment]
> If ring doesn't support mips then you can't. Maybe it will be possible to switch to rust-crypto crates if they have been audited but not for now.

Ok thank you.
