### ISSUE TITLE
Decoding JWKs

### ISSUE THREAD

**Issue by mladedav** [Keats/jsonwebtoken#229]
#226 asked about pulling and parsing the keys from well known URIs. I get that people should download the keys themselves, but would it be possible for the library to at least parse them, or provide JWK types to let users parse it into those which could be then used to create DecodingKey?

I would be happy to help if this was something that could be added to the library.

**Comment by Keats** [comment]
It's already the case in v8 beta, have a look at that example: https://github.com/Keats/jsonwebtoken/blob/next/examples/auth0.rs
You can try it from crates.io as well

**Comment by mladedav** [comment]
Thank you very much.

**Comment by mladedav** [comment]
Since I found in the v8 PR that you're testing functionality and gathering feedback before release I just want to report that all seems to work well here. I'm using Auth0 and there seem to be no issues.

**Comment by Keats** [comment]
perfect, that's good to hear
