### ISSUE TITLE
dangerous_insecure_decode_with_validation removed in 8.0

### ISSUE THREAD

**Issue by thrykol** [Keats/jsonwebtoken#236]
CHANGELOG.md only indicates that `dangerous_unsafe_decode` was removed in the 8.0 build.  However, it appears that `dangerous_insecure_decode_with_validation` and `dangerous_insecure_decode` were both also removed.  Was this intentional?  If so, it would be good to update the CHANGELOG.md to reflect that change as well.

**Comment by Keats** [comment]
Yes, it's missing on the changelog

**Comment by Keats** [comment]
It was redundant with the changes to the Validation allowing the same thing

**Comment by thrykol** [comment]
You're correct.  Apologies, as I was searching for the function name so overlooked it.

**Comment by EliseZeroTwo** [comment]
Is `dangerous_insecure_decode` really redundant? The `decode` function takes a key, `dangerous_insecure_decode` did not. Having to create a garbage key just to pass it around feels wrong.

**Comment by Keats** [comment]
It's a few more lines but not the main use of the crate so I think it's ok. It helps convey the insecure aspect imo

**Comment by horacimacias** [comment]
in case anybody is looking for the snippet to use now (again make sure you know what you're doing), something like this should help:

```rust
let mut validation = Validation::default();
validation.insecure_disable_signature_validation();
let decoded = jsonwebtoken::decode::<Something>(
    token,
    &DecodingKey::from_secret(&[]),
    &validation,
)?;

```
