### ISSUE TITLE
`decode` returns ExpiredSignature error when the `exp` field is missing

### ISSUE THREAD

**Issue by gbaranski** [Keats/jsonwebtoken#239]
Hi, the `decode` returns ExpiredSignature error when the `exp` field is missing, is that the expected behaviour?

In my case the token has the `exp` field, which is defined as `Option<DateTime<Utc>>`, so that's not always there, and the code which looks like that:

```rust
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenClaims {
    pub sub: Uuid,
    #[serde(with = "chrono::serde::ts_seconds_option")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub exp: Option<DateTime<Utc>>,
}

let key = b"the-key";
let token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4Njg5M2MzMC00YmM3LTRhYWItYTg2NS1mYzdmZThhYmFiMDcifQ.bm2xVzyNq_ql-dLefhPV-aTqzqfsx8ld7ahzgO_brG4";
let mut validation = Validation::default();
validation.required_spec_claims.remove("exp");
let data: TokenData<TokenClaims> = decode(token, &DecodingKey::from_secret(key), &validation).unwrap();
```

**Comment by Keats** [comment]
`required_spec_claims` only checks for the presence/absence of the field. `validate_exp` is still set to `true` in your example. There's no way to say "only validate if the field is present".

**Comment by Keats** [comment]
It should work in 8.1.0
