### ISSUE TITLE
ring-0.16.20 compile error

### ISSUE THREAD

**Issue by ArunGust** [Keats/jsonwebtoken#246]
I got below error.(env: rustc 1.61.0-nightly (d53246fed 2022-03-25)) probably jsonwebbtoken ring dependency 

registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\cpu.rs:257:13
|
165 | macro_rules! features {
| --------------------- when calling this macro
...
257 | aarch64_apple: true,
| ^^^^^^^^^^^^^ no rules expected this token in macro call

Compiling h2 v0.1.26
error[E0425]: cannot find value AES in module cpu::arm
--> registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\aead\aes.rs:381:65
|
381 | if cpu::intel::AES.available(cpu_features) || cpu::arm::AES.available(cpu_features) {
| ^^^ not found in cpu::arm
|
help: consider importing this constant
|
15 | use crate::cpu::intel::AES;
|

error[E0425]: cannot find value PMULL in module cpu::arm
--> registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\aead\gcm.rs:315:26
|
315 | || cpu::arm::PMULL.available(cpu_features)
| ^^^^^ not found in cpu::arm

error[E0425]: cannot find value ARMCAP_STATIC in this scope
--> \registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\src\cpu.rs:235:41
|
235 | if self.mask == self.mask & ARMCAP_STATIC {
| ^^^^^^^^^^^^^ not found in this scope

Compiling flate2 v0.2.20
For more information about this error, try rustc --explain E0425.
error: could not compile ring due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Keats** [comment]
It seems like that issue should go in the ring repo?
