### ISSUE TITLE
Only able to turn JWK into RSA DecodingKey

### ISSUE THREAD

**Issue by EliseZeroTwo** [Keats/jsonwebtoken#248]
The current JWK implementation appears to be only for the very specific usecase of fetching decoding RSA keys from a JWK set endpoint as you can only turn a JWK into a `DecodingKey` if it is an RSA key as the only method provided is `from_rsa_components`. You also cannot create an `EncodingKey` from components.

**Comment by Keats** [comment]
Honestly I've only added the JWK types because I wanted to have an easy example with Auth0. If someone wants to be able to use JWK with elliptic curves, I would take a PR but won't implement it myself.

**Comment by EliseZeroTwo** [comment]
I have already implemented this since opening the issue: https://github.com/eliseZeroTwo/jsonwebkey

I am willing to rework the JWK types based on this if it is wanted but as the code I made is based on the existing (but unmaintained) JWK crate (https://github.com/nhynes/jwk-rs/) I am not sure if this is something you would be happy with?

**Comment by Keats** [comment]
As mentioned in https://github.com/Keats/jsonwebtoken/blob/master/src/jwk.rs#L4-L5 the types for the JWK comes from a pretty complete crate I think?
I don't really want to go full JWK support in this crate, just enough for 90% of users to have enough types to handle the usual oauth dance with eg https://www.ory.sh/docs/hydra or Auth0. I don't know if that conflicts with what you need.

**Comment by EliseZeroTwo** [comment]
Ok, thank you for the response. The lack of handling of private keys does conflict with what I was doing but that is not a problem, as you clarified this is not the intention of this crate. I'm going to close this issue.
