### ISSUE TITLE
Getting Error `Missing required claim: exp` even when `validate_exp` is false

### ISSUE THREAD

**Issue by LuisOsta** [Keats/jsonwebtoken#261]
```
pub fn verify_token(secret: String, token: String) -> Result<Claims, jsonwebtoken::errors::Error> {
    let mut validation = jsonwebtoken::Validation::new(JWT_ALGORITHM);
    validation.validate_exp = false;
    let data = jsonwebtoken::decode::<Claims>(
        &token,
        &jsonwebtoken::DecodingKey::from_secret(secret.as_bytes()),
        &validation,
    )?;

    Ok(data.claims)
}
```
This is the way that I'm using the `jsonwebtoken` library where the `Claims` struct is
```
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct Claims {
    pub sub: String,
    pub name: String,
}
```

**Comment by LuisOsta** [comment]
I saw https://github.com/Keats/jsonwebtoken/issues/239. But why not have it also not care if its absent/present if `validate_exp` is set to false?

**Comment by Keats** [comment]
> But why not have it also not care if its absent/present if validate_exp is set to false?

Presence/absence and validation are two different things. You might want to enforce having an `exp` field but not want to validate it with the crate because you're not using the standard timestamp for example.
