### ISSUE TITLE
[Feature Request]JWKS Support

### ISSUE THREAD

**Issue by lubitelpospat** [Keats/jsonwebtoken#263]
Many providers, e.g. Apple, ship their public keys in form of JWKS for JWT validation. Now, many users have to create dedicated micro services in other languages, rely on self-written implementations or use third-party libraries along with this project as a workaround. However, it would be relatively easy to natively integrate JWKS support into this library: one needs to retrieve **kid** field from JWT,  match it against **kid** fields in JWKS, and validate the JWT against the corresponding JWK. I request this feature to be added to this library, and if the maintainer(s) of this project do not mind, I cat fork, add feature and create a PR.

**Comment by Keats** [comment]
It's already kinda supported? https://github.com/Keats/jsonwebtoken/blob/master/examples/auth0.rs

**Comment by lubitelpospat** [comment]
Thank you for your immediate response! Sorry, for some reason I didn't notice it in the documentation. Again, thank you for your time!

**Comment by Keats** [comment]
No, not planned.

**Comment by sandeepkunusoth** [comment]
hi thanks for reply. i have 1 more question does this library support jwks fetching during initialization or we should manually fetch jwks keys and pass it to validation like JWKS_REPLY here https://github.com/Keats/jsonwebtoken/blob/245858fdf3fade3ef176d49d00334dec9e9f6b0b/examples/auth0.rs#L9
