### ISSUE TITLE
Compile error with pinned version of rust toolchain

### ISSUE THREAD

**Issue by cduvray** [Keats/jsonwebtoken#268]
Hello,

The project does not compile any more with pinned version of the toolchain 1.56.0 (ci.yml).

You should either:
-  update the pinned version 1.59 minimum (time = "0.3" -> 0.3.15)
- or force the version of "time" to ("=0.3.9") 

Or is there an other solution to be able to pass the CI checks?

C.

**Comment by Keats** [comment]
Let's bump the pinned CI version
