### ISSUE TITLE
Decode token without validation?

### ISSUE THREAD

**Issue by mrichman** [Keats/jsonwebtoken#295]
Is it possible to decode a token without performing validation? I have unit tests where I need to retrieve just the claims from the token without calling out to a JWKS URL for validation purposes.

**Comment by Keats** [comment]
Decode the token after using https://docs.rs/jsonwebtoken/latest/jsonwebtoken/struct.Validation.html#method.insecure_disable_signature_validation

**Comment by mrichman** [comment]
I did `validation.insecure_disable_signature_validation()` but I still get `ExpiredSignature`. Anything else I can do?

**Comment by Keats** [comment]
You need to set `validate_exp` and `validte_nbf` to `false` as well

**Comment by mrichman** [comment]
That did the trick, thanks!
