### ISSUE TITLE
Support for aud field accepting both a String and a List of Strings

### ISSUE THREAD

**Issue by hvdrumsta** [Keats/jsonwebtoken#299]
Hi there, according to [JWT spec](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3), the `aud` could be either an array of Strings or if it's a single element it could be just a String that's not inside a list.

I was wondering how to decode a JWT into a claims structure that could accept both a List of String and a single String?

**Comment by Keats** [comment]
You will need to make the aud an enum like in https://github.com/Keats/jsonwebtoken/blob/master/src/validation.rs#L181-L186

This library already handles both cases

**Comment by hvdrumsta** [comment]
Thank you, that worked.
