### ISSUE TITLE
Type mismatch error between a string and sequence

### ISSUE THREAD

**Issue by jain-tarun** [Keats/jsonwebtoken#305]
When trying to decode the token to extract the Token Data, you need to pass in the Claims Struct as described in the documentation here : https://docs.rs/jsonwebtoken/latest/jsonwebtoken/fn.decode.html

Now there are claims like 'amr' that can have a value string or a sequence of strings.
amr : pwd OR amr : {rsa, mfa}

The above results in the code only working for the type you declare your amr field in the Claims struct and it fails for the other type and vice versa. I think the problem is to do with the code -> https://docs.rs/jsonwebtoken/latest/src/jsonwebtoken/serialization.rs.html

To reproduce the issue -> Feed the tokens with amr : pwd AND amr : {rsa, mfa} to the decode function and it should fail for 1 case.

**Comment by Keats** [comment]
Well it's up to you to define your amr field as an enum and let serde serializ the right one? I don't think it's anything to do with this library in particular
