### ISSUE TITLE
How to deserialize certs endpoint in Keycloak?

### ISSUE THREAD

**Issue by SamTV12345** [Keats/jsonwebtoken#306]
I have the problem that one algorithm in the certs endpoint is not recognized by your library. Could you please give a sample on how to get around this? I am fine with RS256 algorithm I just need to get rid of RSA-OAEP that is also deserialized from serde.

**Comment by Keats** [comment]
Duplicate of https://github.com/Keats/jsonwebtoken/issues/252

**Comment by SamTV12345** [comment]
Found it out on my own. Just create a new model, drop everything that is not RSA256 and then serialize and deserialize it.
