### ISSUE TITLE
[RFC] Migrate to ring-0.17

### ISSUE THREAD

**Issue by xiangzhai** [Keats/jsonwebtoken#309]
Hi @Keats 

ring-0.17 [added a Rust ChaCha20 implementation](https://github.com/briansmith/ring/commit/c6d8f58ad0af95dd5db18d02290eec16cf440757) and [provided an implementation of `bn_mul_mont`](https://github.com/briansmith/ring/commit/81f4e8d07da3f2ccc57f69a91245b41e6d764a1c) that works on all targets that don't have an assembly language implementation.

The `fallback` (implemented in Rust) might fixed #246 for darwin aarch64.  And it also [works for LoongArch64](https://github.com/briansmith/ring/pull/1565) target which  don't have optimized assembly language implementation.

I want to help [migrating to ring-0.17](https://github.com/xiangzhai/jsonwebtoken/tree/ring-0.17) when ring-0.17.0 upstream was ready.

Could you give me some suggestion please?

Thanks,
Leslie Zhai

**Comment by Keats** [comment]
We're not in a hurry to upgrade, let's wait till it's released for a while before upgrading it as well.

**Comment by xiangzhai** [comment]
Hi @Keats 

I see :)

Thanks,
Leslie Zhai

**Comment by spruce** [comment]
Some time ago I tried to work with jsonwebtokens on my MacBook Pro M1. It wouldn't compile. The fix was to require ring version of at least 0.16.19.

Would it be possible to upgrade the dependency to at least that?

**Comment by Keats** [comment]
We are not hardcoding any specific version for ring so a `cargo update` should work, unless another dependency is requiring something specific.

**Comment by xiangzhai** [comment]
Hi @spruce 

> The fallback (implemented in Rust) might fixed https://github.com/Keats/jsonwebtoken/issues/246 for darwin aarch64.

You could try https://github.com/xiangzhai/ring/tree/0.16.20-loongarch64-fallback 

Thanks,
Leslie Zhai

**Comment by ravenclaw900** [comment]
Now that ring 0.17.0 is released, are there plans to move forward on this?

**Comment by Keats** [comment]
No need to rush, it's been released 3 days ago. We can hold off a bit until it's been tested a bit more

**Comment by Keats** [comment]
It's in 9.2.0
