### ISSUE TITLE
The pinned tests fails

### ISSUE THREAD

**Issue by giraffate** [Keats/jsonwebtoken#314]
https://github.com/Keats/jsonwebtoken/actions/runs/5027342878/jobs/9016716260#step:5:77
> error: package `regex v1.8.1` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.59.0

The pinned version is 1.59.0. The regex is a part of the dev-dependencies. So, would the pinned version be updated to 1.60.0? (In this project, I don't know that whether the pinned version is different from msrv.)

**Comment by Keats** [comment]
Hmm that's an interesting situation. I guess we can pin criterion for now since it's dev only? (I'm guessing regex is in criterion)

**Comment by giraffate** [comment]
Yes, regex is dependencies of criterion. I don't know this is the good way, but it works when we pin regex directly in dev-dependencies.
https://github.com/Keats/jsonwebtoken/pull/315

**Comment by Keats** [comment]
Fixing it by bumping the pinned version. Thanks!
