### ISSUE TITLE
`decode` panics on `wasm32-unknown-unknown` when `validate_exp` is `true`

### ISSUE THREAD

**Issue by BrandonDyer64** [Keats/jsonwebtoken#339]
`fn get_current_timestamp() -> u64` uses `SystemTime::now()` to get the current unix timestamp. Unfortunately, `SystemTime` functions panic on `wasm32-unknown-unknown`.

There are a couple of approaches to fix this:

1. Switch to `chrono` for getting the timestamp
    ```rust
    pub fn get_current_timestamp() -> u64 {
        chrono::Utc::now().timestamp() as u64
    }
    ```
1. In `Validation`, allow the user to supply a timestamp
    ```rust
    /// Supply a custom timestamp for checking `exp` and `nbf` claims.
    /// If `None`, will use `SystemTime::now()`.
    ///
    /// Defaults to `None`.
    pub current_timestamp: Option<u64>,
    ```

As a long-term solution, I prefer option 2 as it adds no cost, doesn't inflate the dependency tree, and allows for better customization.

**Comment by Keats** [comment]
3. Do like Chrono does: https://docs.rs/chrono/latest/src/chrono/offset/utc.rs.html#84-108 and have a different function if it's in WASM

2 is not great because that means you now need to set the timestamp everytime you use the library while I'm expecting a lot of `Validation` struct to be mostly static

**Comment by BrandonDyer64** [comment]
@Keats There is an open PR that does what you're saying (#318), but it needs to be merged

**Comment by Keats** [comment]
Yes. As mentioned in the PR, it's missing CI

**Comment by BrandonDyer64** [comment]
@Keats The structure of `Validation` does not generally imply being static as the `sub` field is user specific. The original PR I submitted allowed for a user to choose to add a custom `exp` timestamp if they want.

I made another PR that uses `js_sys` when on `wasm32-unknown-unknown`, but I heavily urge you to please find a way to let the user specify a timestamp for validation
