### ISSUE TITLE
[Bug] Error(MissingRequiredClaim("exp"))

### ISSUE THREAD

**Issue by Baiyuetribe** [Keats/jsonwebtoken#348]
## Env
jsonweb: latest
## how to reproduce 
```rust
    let mut validation = jwt::Validation::default();
    validation.validate_exp = false;
 ```
diasble exp check,then errors ` Error(MissingRequiredClaim("exp"))`

## more bug
![image](https://github.com/Keats/jsonwebtoken/assets/43716063/d9efa098-3602-4aff-910d-d59f21380cdc)
![image](https://github.com/Keats/jsonwebtoken/assets/43716063/957d55c9-14be-47cb-b273-ee80a2acd50f)

## target
How do I disable exp authentication properly?

**Comment by Keats** [comment]
Not a bug report: see https://docs.rs/jsonwebtoken/latest/jsonwebtoken/struct.Validation.html#method.set_required_spec_claims

**Comment by Keats** [comment]
That's not what I said: look at the example in https://docs.rs/jsonwebtoken/latest/jsonwebtoken/struct.Validation.html and https://github.com/Keats/jsonwebtoken/blob/master/src/validation.rs#L691-L693 for an example in a test

**Comment by Baiyuetribe** [comment]
thanks,it works~
