### ISSUE TITLE
Support millisecond validation on `exp` of Claims

### ISSUE THREAD

**Issue by 1552980358** [Keats/jsonwebtoken#355]
JVM language usually use UTC timestamp in millisecond (`System.currentTimeMillis()`), and I have a requirement on checking the timestamp at database field of exp timestamp on both Rust and JVM server. Is there is any posibility on supporting validation of exp with support of millisecond? (Like adding a flag in Validation prompting the timestamp format is UTC in millisecond)

**Comment by Keats** [comment]
Nope, if exp is in milliseconds then it's not a valid JWT. You will have to do it by hand if you want to support that.

**Comment by 1552980358** [comment]
> Nope, if exp is in milliseconds then it's not a valid JWT. You will have to do it by hand if you want to support that.

I see, sorry for my issue
