### ISSUE TITLE
Make TokenData struct public

### ISSUE THREAD

**Issue by naerbnic** [Keats/jsonwebtoken#37]
Currently the TokenData struct does not appear to be made public, and thus does not appear in the documentation. To my understanding, this will eventually cause an error during building as well. A top-level `pub use` should handle this, as you do with `Header`.

**Comment by Keats** [comment]
It was made public in https://github.com/Keats/jsonwebtoken/commit/5758c0008cc9e42f4152b9f121f67d5450c1eaa6 but I didn't publish a new version yet, probably tomorrow or tuesday

**Comment by Keats** [comment]
It's in the latest version on crates.io
