### ISSUE TITLE
大佬看下，生成的token，我定了30秒有效期，超过了30秒怎么还能解码呢，

### ISSUE THREAD

**Issue by pshuchuan** [Keats/jsonwebtoken#375]
#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    id:i32,
    email:String,
    exp: u64,
}

pub fn  token(id:i32,email:String) -> String{
    let key = b"hmhometoken";
    println!("加30秒之前：{}",Utc::now().timestamp());
    let expiration_time = Utc::now() + Duration::try_seconds(20).unwrap();
    
    let time =expiration_time.timestamp();
    println!("加30秒之后：{}",time);
    // let expiration_time = Utc::now() + Duration::days(365); 
    
    let myclaims =
     Claims {
        id,
        email,
        exp:time as u64,
    };
    let header =Header { kid: Some("signing_key".to_owned()), alg: Algorithm::HS512, ..Default::default() };
    // 生成令牌
    
    println!("生成令牌:{}",Utc::now());
    let token = match encode(&header,&myclaims,&EncodingKey::from_secret(key),) {
        Ok(t) => {
          t
        }
        Err(e) => {
            eprintln!("无法生成令牌: {}", e);
             format!("无法生成令牌:{}",e)} };
        token
}

pub fn parse_token(token: String) -> Result<Claims, MyError> {
    let key = b"hmhometoken";
    let mut validation = Validation::new(Algorithm::HS512);
validation.validate_exp = true;

    decode::<Claims>(&token, &DecodingKey::from_secret(key), &validation)
        .map(|data| data.claims)
        .map_err(|e| MyError::new(format!("令牌验证失败: {}", e)))
}

**Comment by headironc** [comment]
I have the same problem. During one minute after expiration, the token still works.

**Comment by headironc** [comment]
2024-03-25T16:58:07.508497Z DEBUG middlewares: Access token: eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSJ9.eyJleHAiOjE3MTEzODU4MzEsImlhdCI6MTcxMTM4NTUzMSwic3ViIjoiNjYwMDY2NTFlYzQ1YzY5NzJhNzlkZmI5In0.bA7NWrKaw8cMBid4gNQ89bAi83DFsS9kw0qVvaECoisuLl62AYZ6ecA-H5ce1DTuWFE4VPdb7OKf5tanAz1rDg
2024-03-25T16:58:07.512103Z DEBUG middlewares: Claims: Claims { exp: 1711385831, iat: 1711385531, sub: "66006651ec45c6972a79dfb9" }

<img width="843" alt="Screenshot 2024-03-26 at 00 58 44" src="https://github.com/Keats/jsonwebtoken/assets/19648989/292d72df-9f1a-4f0b-a856-c92bb21e4d15">

**Comment by headironc** [comment]
<img width="2123" alt="Screenshot 2024-03-26 at 01 00 40" src="https://github.com/Keats/jsonwebtoken/assets/19648989/ec31d2f4-3110-4e0b-8b83-28111a3e3d62">

**Comment by headironc** [comment]
<img width="2306" alt="Screenshot 2024-03-26 at 00 58 54" src="https://github.com/Keats/jsonwebtoken/assets/19648989/410fa2c2-d98f-4f00-b662-987e8f8faac9">

**Comment by headironc** [comment]
> Google translated the title but there is automatic leeway for the validation.

Oh, i see
