### ISSUE TITLE
Don't fail if `typ` is not present in the token. 

### ISSUE THREAD

**Issue by mhseiden** [Keats/jsonwebtoken#38]
Although the standard requires it, not all jwt providers are standards compliant. It would be nice if this lib was more tolerant of the missing field.

**Comment by Keats** [comment]
Hmm I don't think I would want that in the library. Is there a known provider that gives invalid JWT?

**Comment by bhendo** [comment]
@Keats Google does not seem to provide `typ`

**Comment by Keats** [comment]
Hum I see, I guess it should be an `Option` then for the next major version

**Comment by Keats** [comment]
Fixed in 3.0
