### ISSUE TITLE
Unsafe default behavior

### ISSUE THREAD

**Issue by idubrov** [Keats/jsonwebtoken#41]
If algorithm is not explicitly enforced via Validation, library will happily accept "forged" token where RS256 algorithm is replaced with HS256 and token is signed with RSA public key used as a secret.

Not sure what could be done here as this isn't the library issue per se, but rather unsafe usage of it. Maybe warning in the documentation?

Alternatively, library could accept the only one algorithm as a parameter. Since key you need to pass to decode is specific to the algorithm anyway, the current signature of (token: &str, key: &[u8], validation: &Validation) is not very useful.

[More details](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/)

**Comment by idubrov** [comment]
Or, even better, instead of accepting key as a slice, it should accept closure which would return key based on provided algorithm type and "kid" (optional).

This would also avoid parsing header twice (since you already parsed it at the point you invoke "verify").

**Comment by Keats** [comment]
Eh that's weird, I don't remember why Validation::algorithms is an `Option`, it shouldn't be.

**Comment by Keats** [comment]
#42 removes the `Option` for algorithms so the end user will need to explicitely say which alg are allowed for starter

**Comment by Keats** [comment]
I believe it's fixed now as the algorithm validation is now mandatory
