### ISSUE TITLE
Token decoding does not crash with an error when the token has expired

### ISSUE THREAD

**Issue by Edgar200021** [Keats/jsonwebtoken#412]
![2024-10-15-141021_hyprshot](https://github.com/user-attachments/assets/118a2134-10af-47ec-ba65-7bd10837b483)
![2024-10-15-140929_hyprshot](https://github.com/user-attachments/assets/349ba3f8-215a-4848-b608-951987640645)
![2024-10-15-140726_hyprshot](https://github.com/user-attachments/assets/964a13dd-1c89-483d-9340-101bca55371b)

Hi, I noticed that during token decoding I don't get an error when the token expires, in this case (according to the photo) the token is not valid for 7 seconds, but still no error.

**Comment by Keats** [comment]
There is some leeway by default: https://github.com/Keats/jsonwebtoken/blob/master/src/validation.rs#L39-L43
