### ISSUE TITLE
Is jsonwebtoken able to validate Firebase Auth token ?

### ISSUE THREAD

**Issue by hugues31** [Keats/jsonwebtoken#44]
Hello,
I try to figure out how to validate a jwt issued by Firebase Auth service.
I try with this code with no chance :
```rust
let private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgk******3sPj2xm0C\nl76YeEQy0+BJqSvNq5Z05g==\n-----END PRIVATE KEY-----\n";
let mut validation = Validation::new(Algorithm::RS256);
let header = decode_header(&token).unwrap();
eprintln!("Token  header: {:?}", header);

let token = decode::<Claims>(&token, private_key.as_ref(), &validation);
eprintln!("Token : {:?}", token.unwrap());
```

And Claim struct:
```rust
#[derive(Debug, Serialize, Deserialize)]
struct Claims {
    sub: String
}
```

The header is correctly parsed but the claim cannot be verified (InvalidSignature). Since I'm new to this, maybe I did something wrong, can someone help me please ?

**Comment by Keats** [comment]
The private key needs to be in DER format, there are some notes on how to convert PEM -> DER there: https://github.com/Keats/jsonwebtoken/blob/master/tests/notes.md

**Comment by hugues31** [comment]
Thanks for your answer :) I read that part and convert my key but I end up with: 
private_rsa_key.der
`0����<�Z�O��
pȷ=S2�ŅY�]#\��"Q��ݘ0�I�@�?��[��G:�|�򮗩)slZ3�e74�$2��B��b��]���=�W$F)?�v��3^�R|�R�P�{�t�j�Y튠���~���X�L��
ש�>y���Ō
�D��-�1�_լ�?��#$
����<.�ǵ��,1�@�I�,�D��g��4ĩ�&WGx�mh�7�n���N@��u���^���+�d�a��ڿ�X�R��
�#��c�d(JƲ��xbIߑ���!AG��ҽ����=��.�����u������Nn�ΝS
�@��&�_Ļ1?���'�5{���XR��&��3K�F`

How can this work ?

**Comment by Keats** [comment]
(Hopefully it's not a private key in use you've posted, otherwise you need to change it).

DER format is binary, here's an example on how to encode/decode tokens using RSA: https://github.com/Keats/jsonwebtoken/blob/master/tests/rsa.rs#L15-L19

**Comment by hugues31** [comment]
No I cropped the key haha. Thanks for your help, I'll try with that
