### ISSUE TITLE
Add a way to get the header + payload without verifying the signature

### ISSUE THREAD

**Issue by mike-engel** [Keats/jsonwebtoken#48]
Hey! I've gotten a new issue on my cli tool (https://github.com/mike-engel/jwt-cli/issues/4) which was fixed in 3.0 with `typ` being optional. 3.0 did, however, break one use case of my tool which is to just see the contents of a JWT without verifying the signature (debugging, etc). I used to use the `validate_signature` option in `Validation`, which was removed in 3.0.

Would you be open to having a separate method to just decode a token without verification? I looked through a couple of issues and didn't see the reason for removing `validate_signature`, but I'm sure there was one.

Thanks!

**Comment by Keats** [comment]
The reason for removing it was to not have an insecure option as part of the main function. I think it would be fine to add something like `dangerous_unsafe_decode` to be added as an additional method, without touching the main `decode`.

**Comment by Keats** [comment]
It's in 4.0.1
