### ISSUE TITLE
Claim validation assumes all date fields are serialized as `i64`

### ISSUE THREAD

**Issue by 1wilkens** [Keats/jsonwebtoken#50]
[`validation::validate`](https://github.com/Keats/jsonwebtoken/blob/9056a2912f68a9c1af4d5493606cb01190856dfa/src/validation.rs#L112) assumes all relevant date fields are serialized as `i64` as they are passed to `serde_json::from_value::<i64>`.
Per default this is not the case for e.g. `chrono::DateTime` which seems to be the de-facto standard type to represent timestamps.
It took me several hours to realize the error happens in `validate` as the error message said something along the lines of `found string "<valid timestamp with timezone string>". expected i64` which I interpreted as a failure in parsing the claims themselves.
I am not too familiar with `serde` and `chrono` internals but it should be possible to deserialize the complete `chrono::DateTime` and compare this with `now` obtained earlier in the function.
I am a little busy right now, but might whip up a PR in the next days..

**Comment by Keats** [comment]
The spec (https://tools.ietf.org/html/rfc7519#section-4.1.4) says those fields: 

>  Its value MUST be a number containing a NumericDate value

and

>  NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.

So according to the spec the claims must be UTC timestamps which means it's easier to have the validation fields be UTC timestamps as well.
PyJWT (https://pyjwt.readthedocs.io/en/latest/usage.html#expiration-time-claim-exp) does the following: 

> You can pass the expiration time as a UTC UNIX timestamp (an int) or as a datetime, which will be converted into an int. 

and also converts the timestamp in the claims to an int: https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L154

**Comment by 1wilkens** [comment]
I knew I should have looked up the spec first ;)
Okay I think I'll write an example that uses `serde`'s `serialize_with` attribute to demonstrate usage of these date fields then.
Thanks for the quick reply!
