### ISSUE TITLE
Expose claims `Map<_, _>` when decoding

### ISSUE THREAD

**Issue by acheronfail** [Keats/jsonwebtoken#53]
I'm making a library that extends jwt and adds some extra validation to the claims, and have run into a problem. Since I'd like the user of my library to define their `Claims` struct, I don't want to provide the type, but I'd like to perform some validation on it nonetheless.

```rust
// My validate function:
pub fn validate<T: DeserializeOwned>(token: &str, key: &[u8], validation: &Validation) -> Result<TokenData<T>, Error> {
  let token_data = decode::<T>(&token, "secret".as_ref(), &Validation::default())?;
  
  // HERE: I need to perform some validation on the claims.
  // Some fields will be marked as mandatory, etc...
  token_data.claims_map.get("iss").expect("No `iss` claim found");

  Ok(token_data)
}
```

I'd like a way to receive the `Map<String, Value>` [found here](https://github.com/Keats/jsonwebtoken/blob/master/src/serialization.rs#L40) so that I can perform some checks on the payload before returning it to the user. Unfortunately, I can't rely on the user's custom `T` struct since that may not have the claims the library will need to validate.

Could we consider adding another field to the `TokenData` struct which includes the `Map<String, Value>` struct as well?

**Comment by Keats** [comment]
i'm not sure it makes sense to return it as most people don't care about it. How about adding a field to the `Config` that is a hook fn that can be called during decoding and that will receive that map as argument so you can add your own custom validation in it?

**Comment by acheronfail** [comment]
By the `Config` do you mean adding a field to the `Validation` struct?

Something like this?

```rust
// User's custom validation here:
fn my_custom_validator(claims: &Map<String, Value>) -> Result<()> {

}

let mut validation = Validation::default();
validation.custom_validator = my_custom_validator;

// Validation will error with an error indicating that the `custom_validator` failed validation
```

**Comment by acheronfail** [comment]
@Keats Actually, I think I have found a way to make it work similar to what you suggested. I'll update the PR and then you can see what you think!

**Comment by acheronfail** [comment]
For the moment, my current workaround is to serialise and deserialise the decoded claims struct. Thanks to the performance of `serde` the impact is negligible.

```rust
use serde_json::{Map, to_string, from_str};

let token_data = jwt::decode::<T>(&token, &public_key, &validation)?;
let claims_map: Map<_, _> = &from_str(&to_string(&data.claims)?)?;
// ...
```

**Comment by acheronfail** [comment]
For the moment, my current workaround is to serialise and deserialise the decoded claims struct. Thanks to the performance of `serde` the impact is negligible.

```rust
use serde_json::{Map, to_string, from_str};

let token_data = jwt::decode::<T>(&token, &public_key, &validation)?;
let claims_map: Map<_, _> = &from_str(&to_string(&data.claims)?)?;
// ...
```
