### ISSUE TITLE
Incompatible with Rocket atm

### ISSUE THREAD

**Issue by terry90** [Keats/jsonwebtoken#56]
```
error: multiple packages link to native library `ring-asm`, but a native library can be linked only once

package `ring v0.11.0`
    ... which is depended on by `cookie v0.9.2`
    ... which is depended on by `rocket v0.3.14`
    ... which is depended on by `rocket_contrib v0.3.14`
    ... which is depended on by `xxx v0.1.0 (file:///home/xx/xx)`
links to native library `ring-asm`

package `ring v0.12.1`
    ... which is depended on by `jsonwebtoken v4.0.1`
    ... which is depended on by `xxx v0.1.0 (file:///home/xx/xx)`
also links to native library `ring-asm`
```

see https://github.com/briansmith/ring/issues/575

I know this is not the responsibility of jsonwebtoken, but this should be left open until resolved since rocket is a well known framework.

`v2.0.3` is compatible

**Comment by Keats** [comment]
Published v5 which uses ring 0.13, should be fine now

**Comment by Keats** [comment]
You will need to update your `cookie` crate version to 0.11

**Comment by terry90** [comment]
The `cookie` crate is from `rocket`, not from my `Cargo.toml`

**Comment by Keats** [comment]
Ah then you will need to wait for a new release of rocket that contains the
updated version of cookie. The git repo (
https://github.com/SergioBenitez/Rocket/blob/master/core/http/Cargo.toml)
already points to a cookie that will work with jsonwebtoken v5 so it is
just a matter of time.

**Comment by terry90** [comment]
Great :)
