### ISSUE TITLE
DER from x509 (auth0)

### ISSUE THREAD

**Issue by aep** [Keats/jsonwebtoken#62]
trying to use this with auth0, where its only possible to get the x509 certificate that is used for signing

```
openssl x509 -in auth0.pem -outform DER -out auth0.der
```

doesnt seem to work. i'm getting ' Error(InvalidSignature)'. 
the same token validates fine on jwt.io with that certificate.

**Comment by aep** [comment]
this seems to work, but i'm not sure if this is safe because it strips the rest of the certificate:

```
openssl x509 -pubkey -noout -in  auth0.pem  > auth0_pkey.pem
openssl rsa -pubin -in auth0_pkey.pem  -RSAPublicKey_out -outform DER -out auth0.der
```

**Comment by Keats** [comment]
Sorry for the delay

The commands in the last message *look* fine to me

**Comment by Keats** [comment]
@aep can this be closed?

**Comment by aep** [comment]
yes thanks!
