### ISSUE TITLE
PEM -> DER public key conversion

### ISSUE THREAD

**Issue by pythoneer** [Keats/jsonwebtoken#63]
Hi, i tried to use this library to secure a micro service but i was unable to verify the signature based on the public key from our auth service. I was converting the public key from the PEM into the DER format but without success. I have read the notice in the README and found a [related issue](https://github.com/Keats/jsonwebtoken/issues/55) but all this suggested is that i have to create the DER file out of the `private key` from the auth server. I am not an expert in crypto and i don't really know why this is necessary in your specific case (and why i cannot just build the DER from the public PEM key like `openssl rsa -pubin -inform PEM -in public_key.pem -outform DER -out public_key.der`) but isn't this a total deal breaker to require the `private key` in an asymmetric crypto schema?  

I am not getting the `private key` from our auth department to create a `public key` in DER format to use this library. Am i missing something or is this library just not suitable for my case?

**Comment by Keats** [comment]
Not at the computer but you can decide a token using the public key in der
format, check tests/rsa.rs

**Comment by Keats** [comment]
A pem file is a der file that has been base64'd so you don't need access to
the private key. I'll have a look tomorrow.

**Comment by pythoneer** [comment]
Sure, i am just wondering why the conversion with `openssl` is "wrong"? My problem is basically the same as in this [related issue](https://github.com/Keats/jsonwebtoken/issues/55) i think the `openssl` command is just wrong?
```
openssl rsa -pubin -inform PEM -in public_key.pem -outform DER -out public_key.der
```

The reason why i am assuming that i need the `private key` is because of this part in the README

``` 
RSA

jsonwebtoken can only read DER encoded keys currently. If you have openssl installed, you can run the following commands to obtain the DER keys from .pem:

// private key
$ openssl rsa -in private_rsa_key.pem -outform DER -out private_rsa_key.der
// public key
$ openssl rsa -in private_rsa_key.der -inform DER -RSAPublicKey_out -outform DER -out public_key.der

If you are getting an error with your public key, make sure you get it by using the command above to ensure it is in the right format.
```

and the section in the related issue

```
# convert private.pem (above) to private.der.
openssl rsa -in private.pem -outform DER -out private.der

# generate the public.der from private.der
openssl rsa -in private.der -inform DER -RSAPublicKey_out -outform DER -out public.der
```

both use the term `private.pem`/`private.der` that is suggesting a `private key` file to me.

Thanks, and have a nice day :)

**Comment by pythoneer** [comment]
Thanks for the clarification! I try to test it is soon as possible. Considering that you have a test for this case i see this issue as closed. Thx for your fast response and explanation!
