### ISSUE TITLE
validate_exp when exp is not in token claims

### ISSUE THREAD

**Issue by mehcode** [Keats/jsonwebtoken#65]
Looking at https://github.com/Keats/jsonwebtoken/blob/master/src/validation.rs#L128

It seems odd that if `exp` is not in the token validation fails. Otherwise `exp`-less tokens insta-fail with `Validator::default()`.

I'd vote for changing this so that its not an error if exp is asked to be validated and exp is not present.

**Comment by Keats** [comment]
`jsonwebtoken` differs a bit from the spec in some points to avoid footguns like not having the `none` algorithm.
The default should be a good one and having a JWT without `exp` is a bad idea so it is worth it making the user realise what is going on. The change is not that big: `Validation { validate_exp: false, ..Validation::default() };` if you really need that.

**Comment by Keats** [comment]
Although looking at the code again, it seem that `iat` and `nbf` should be validated automatically if present instead of having to set it up in `Validation`

**Comment by jhpratt** [comment]
@Keats Perhaps the error message could indicate that the expiration is _not present_ and not _expired_? When testing a very basic encode/decode, I get an `ExpiredSignature` error, which is counterintuitive to say the least.

**Comment by Keats** [comment]
A different error kind would make sense yes

**Comment by PrismaPhonic** [comment]
To be honest I'm not seeing anywhere in the documentation how you set an expiration on a token.  Can someone point me in the right direction?  It doesn't seem to be any of the Header fields

**Comment by Keats** [comment]
Adding expiration is done on a claim, like in the struct in https://github.com/Keats/jsonwebtoken#how-to-use: https://tools.ietf.org/html/rfc7519#section-4.1.4

The validation itself uses the UTC timezone so the `exp` field should be a UTC timestamp.
