### ISSUE TITLE
How to set expiration with examples.  

### ISSUE THREAD

**Issue by technetos** [Keats/jsonwebtoken#67]
Ok so I am trying to use this crate and I keep getting `expired signature` when I try and decode my jwt when the client sends it back to me.  I have a field in my struct that gets encoded as a jwt called `exp` of type `usize` and ive set it to `3600` (1 hour) but it just seems to be ignored.  Am I doing something wrong and if so, what is the correct way to set the expiration time of the token?

Nevermind, I realized I had to use now + an hour.  :smile:  closing issue.

**Comment by Figments** [comment]
I can't seem to figure this one out. You say "Now + an hour", but what does that even mean? Are you using `std::time::SystemTime::now()` and somehow casting that as a `usize` value? I can't seem to do that.

**Comment by Keats** [comment]
The `exp` field should be a UTC timestamp, so now + 1h would mean current UTC timestamp  + 3600

**Comment by Figments** [comment]
So then the type of the `exp` field should be from the `std::time` library or `chrono`? Or does it matter?

**Comment by Keats** [comment]
How you get the timestamp doesn't matter, at the end it should be just a UTC timestamp, so a `usize` effectively. In the tests, we do https://github.com/Keats/jsonwebtoken/blob/master/tests/lib.rs#L39 for example.
