### ISSUE TITLE
Submit a PR to jwt.io to update feature support

### ISSUE THREAD

**Issue by brianpeiris** [Keats/jsonwebtoken#71]
The listing for jsonwebtoken on https://jwt.io/#libraries-io seems to be outdated, e.g. it claims you don't support `exp` checking. You can submit a PR to update it at their repo:
https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/master/views/website/libraries/13-Rust.json#L38-L68

**Comment by Keats** [comment]
Thanks, I'll update it after the next release

**Comment by samuela** [comment]
I just submitted https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/386

**Comment by Keats** [comment]
I've made https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/443 to update it again
