### ISSUE TITLE
Provide example using chrono::DateTime

### ISSUE THREAD

**Issue by rakenodiax** [Keats/jsonwebtoken#82]
`chrono` is a very popular date and time library and defaults to serializing as ISO strings instead of timestamps as per the JWT spec. It'd be nice to have an example using the `#[serde(with = "..")]` attribute. I can submit a PR with this example if it is accepted for inclusion.

**Comment by Keats** [comment]
Please do so!

**Comment by rakenodiax** [comment]
@Keats I'll get right on it!
