### ISSUE TITLE
Update Ring to 0.14

### ISSUE THREAD

**Issue by nyarly** [Keats/jsonwebtoken#84]
I appreciate the challenge of chasing Ring's versions, but ATM jsonwebtoken can't be used with rustls (which depends on ring 0.14).

Is that process basically mechanical? i.e. Bump Ring, test, bump version, publish?

**Comment by Keats** [comment]
See https://github.com/Keats/jsonwebtoken/issues/76#issuecomment-475531454

We're trying to get a couple more PRs that are breaking change in before releasing.

**Comment by nyarly** [comment]
Aha, thanks! I didn't see that comment when I was following the flow here.
