### ISSUE TITLE
Keys in test folder

### ISSUE THREAD

**Issue by cfsamson** [Keats/jsonwebtoken#85]
Please specify that in the test folder, the correct public key for `private_rsa_key.pem` is `public_rsa_key_8.pem` and not `public_rsa_key.pem`. Looking at the tests where the `*.der` files are one would assume that it's `public_rsa_key.pem` that is the correct one but I only got the test token verified by using `public_rsa_key_8.pem` and thought there was something wrong in my `base64` to bytearray conversion :)

**Comment by Keats** [comment]
it's better now
