### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by lzutao** [Keats/jsonwebtoken#94]
sccache currently is depending on a patch: https://github.com/Keats/jsonwebtoken/pull/74

**Comment by Keats** [comment]
This PR has been superseded by https://github.com/Keats/jsonwebtoken/pull/91 and is a big breaking change so it won't get released until it has everything needed (https://github.com/Keats/jsonwebtoken/pull/69) as well as testing the usage UX heavily + x509 certificate testing.

**Comment by lzutao** [comment]
No problem then. I could depend on exact commit of this repository.
