### ISSUE TITLE
nbf claims does not validate

### ISSUE THREAD

**Issue by cynner** [Keats/jsonwebtoken#98]
version: `6.0.1`
algorithm: `Algorithm::RS512`

I just add nbf for 4200 sec from now. After 5-10 sec. i try to validate this token but it is pass (set leeway just 60 sec. but it should not be pass). so i think it not validate nbf time. (My purpose is for validate refresh_token that can use after access_token expired or `refresh_token.claims.nbf = access_token.claims.exp` )

* exp is works but nbf not works *

my claims:
```
{
  "exp": 1567042832,
  "nbf": 1567042232,
  "iat": 1567038032
}
```
my validation:
```
  let validation = Validation { 
    leeway: 60,
    algorithms: vec![Algorithm::RS512],
     ..Validation::default() 
  };
  let token_data = match decode::<T>(&token, &PUBLIC_KEY, &validation) {
    Ok(c) => c,
    Err(err) => match *err.kind() {
      ErrorKind::InvalidToken => {
        error!("InvalidToken");
        return None;
      },
      ErrorKind::InvalidAudience => {
        error!("InvalidAudience");
        return None;
      },
      ErrorKind::InvalidIssuer => {
        error!("InvalidIssuer");
        return None;
      },
      ErrorKind::InvalidSignature => {
        error!("InvalidSignature");
        return None;
      },
      ErrorKind::ExpiredSignature => {
        error!("ExpiredSignature");
        return None;
      },
      _ => { 
        error!("TokenError");
        return None;
      }
    },
  };
```

**Comment by Keats** [comment]
The default validation does not validate `nbf` https://github.com/Keats/jsonwebtoken/blob/master/src/validation.rs#L91 since `nbf` is not a super common field. Set `validate_nbf` to true and it should work

**Comment by cynner** [comment]
Oh thanks. It's works.
